/* mdview — user-facing strings of the active mode, in one place so they can
 * be translated. MdStrings.t("key", …values) fills {0}, {1} …
 * The app's older strings are still inline in viewer.js and mdview.py. */
"use strict";
(() => {
  const TABLES = {
    en: {
      "mode.label": "Mode",
      "mode.edit": "Edit source",
      "mode.active": "Active",
      "mode.read": "Read",
      "mode.tip.edit": "{0} (Ctrl+Alt+1, or Ctrl+E)",
      "mode.tip.active": "{0} (Ctrl+Alt+2)",
      "mode.tip.read": "{0} (Ctrl+Alt+3)",
      "active.loadFailed": "Couldn't load the active mode",
      "active.placeholder": "Start writing…",
      "active.label": "Document",
      "link.label": "Link",
      "link.open": "Open",
      "link.edit": "Edit",
      "link.remove": "Remove",
      "link.text": "Text",
      "link.url": "Address",
      "table.rowAbove": "Insert Row Above",
      "table.rowBelow": "Insert Row Below",
      "table.rowUp": "Move Row Up",
      "table.rowDown": "Move Row Down",
      "table.rowDelete": "Delete Row",
      "table.colLeft": "Insert Column Left",
      "table.colRight": "Insert Column Right",
      "table.colMoveLeft": "Move Column Left",
      "table.colMoveRight": "Move Column Right",
      "table.align.left": "Align Left",
      "table.align.center": "Align Center",
      "table.align.right": "Align Right",
      "table.colDelete": "Delete Column",
      "table.delete": "Delete Table",
      "table.wide": "Full Width",
      "table.column": "Column",
      "table.row": "Row",
      "dialog.footnote": "Footnote {0}",
      "menu.cut": "Cut",
      "menu.copy": "Copy",
      "menu.paste": "Paste",
      "menu.pastePlain": "Paste and Match Style",
      "menu.link": "Add Link…",
      "menu.editLink": "Edit Link…",
      "menu.openLink": "Open Link",
      "menu.format": "Format",
      "menu.bold": "Bold",
      "menu.italic": "Italic",
      "menu.strike": "Strikethrough",
      "menu.code": "Code",
      "menu.math": "Formula from Selection",
      "menu.paragraph": "Paragraph",
      "menu.text": "Text",
      "menu.heading": "Heading {0}",
      "menu.bullet": "Bulleted List",
      "menu.ordered": "Numbered List",
      "menu.task": "Task List",
      "menu.quote": "Quote",
      "menu.insert": "Insert",
      "menu.codeBlock": "Code Block",
      "menu.formula": "Formula",
      "menu.table": "Table",
      "menu.rule": "Divider",
      "menu.footnote": "Footnote",
      "menu.edit": "Edit…",
      "menu.copyMarkdown": "Copy as Markdown",
      "menu.delete": "Delete",
      "bar.label": "Formatting",
      "bar.bold": "Bold",
      "bar.italic": "Italic",
      "bar.strike": "Strikethrough",
      "bar.code": "Code",
      "bar.link": "Link",
      "bar.math": "Formula",
      "bar.paragraph": "Paragraph",
      "ask.title": "Apply the changes in this dialog?",
      "ask.text": "Your edits here are not part of the document yet.",
      "ask.apply": "Apply",
      "ask.discard": "Discard",
      "island.code": "{0}, {1} lines. Press Enter to edit.",
      "island.code1": "{0}, one line. Press Enter to edit.",
      "island.math": "Formula: {0}. Press Enter to edit.",
      "dialog.gone": "The block is no longer in the file — your text is on the clipboard",
      "active.large": "Large document — the active mode may be slow",
      "prefs.title": "Settings",
      "prefs.open": "Settings…",
      "prefs.general": "General",
      "prefs.editing": "Editing in the active mode",
      "prefs.newMarkdown": "New Markdown",
      "prefs.page.general": "General",
      "prefs.page.appearance": "Appearance",
      "prefs.page.sidebarPage": "Sidebar",
      "prefs.page.allNotes": "All Notes",
      "prefs.page.editing": "Editing",
      "prefs.page.newMarkdown": "New Markdown",
      "prefs.page.latex": "Formulas",
      "prefs.page.pdf": "PDFs",
      "prefs.page.ai": "Writing Help",
      "prefs.page.about": "About",
      "prefs.group.notes": "Notes",
      "prefs.group.writing": "Writing",
      "prefs.close": "Close",
      "prefs.docZoom": "Text size of a note",
      "prefs.docZoom.hint": "Also Ctrl or Super with + and −; Ctrl+0 for 100 %. Only the note is scaled, not the app around it.",
      "prefs.measure": "Width of the text column",
      "prefs.measure.narrow": "Narrow",
      "prefs.measure.normal": "Normal",
      "prefs.measure.wide": "Wide",
      "prefs.measure.full": "As wide as the window",
      "prefs.hinting": "Sharper text",
      "prefs.hinting.hint": "Letters are set on whole pixels: crisper on a screen of ordinary resolution, their shapes a little changed. Takes effect when the app starts next.",
      "prefs.restartLater": "Takes effect when the app starts next",
      "prefs.ovScope": "Show",
      "prefs.ovScope.all": "All notes, by folder",
      "prefs.ovScope.folders": "One folder at a time",
      "prefs.ovLayout": "As",
      "prefs.ovLayout.tiles": "Tiles",
      "prefs.ovLayout.list": "A list",
      "prefs.paragraphs": "Paragraphs",
      "prefs.pictures": "Pictures",
      "prefs.pdfFormat": "A link to selected text is copied as",
      "prefs.pdfFormat.callout": "A quote in a callout",
      "prefs.pdfFormat.quote": "A quote",
      "prefs.pdfFormat.link": "A link",
      "prefs.pdfFormat.embed": "An embed",
      "prefs.pdfAuto": "Copy as soon as text is selected",
      "prefs.aiKeySection": "Gemini",
      "prefs.aiKey": "API key",
      "prefs.aiKey.hint": "Kept in ~/.config/mdview/.env, readable by you alone. The text around the caret goes to Google when a suggestion is asked for.",
      "prefs.aiKey.placeholder": "Paste a key",
      "prefs.aiKey.save": "Save",
      "prefs.aiKey.remove": "Remove",
      "prefs.aiKey.none": "No key",
      "prefs.aiKey.set": "Key ends in %s",
      "prefs.aiKey.env": "From the environment (GEMINI_API_KEY)",
      "prefs.aiModel": "Model",
      "prefs.aiModel.hint": "Left empty, the app's own choice is asked.",
      "prefs.version": "Version",
      "prefs.guide": "Everything the app does",
      "prefs.guide.do": "Open the guide",
      "prefs.configDir": "Settings folder",
      "prefs.sidebarSort": "Sort notes by",
      "prefs.sort.opened": "Last opened",
      "prefs.sort.name": "Name",
      "prefs.sort.modified": "Date modified",
      "prefs.sidebar": "Sidebar shows, beside notes",
      "prefs.sidebarPdf": "PDFs",
      "prefs.sidebarImages": "Pictures",
      "prefs.sidebarMedia": "Sound and video",
      "prefs.sidebarOther": "All other files",
      "prefs.sidebarOther.hint": "Pictures, sound, video and other files open in their own application.",
      "prefs.ai": "Writing help",
      "prefs.aiComplete": "Suggest the next words while typing",
      "prefs.aiComplete.hint": "In a pause, a continuation shows in grey: Tab takes it, Ctrl+→ the next word, Esc dismisses it. Needs a key for Gemini (below).",
      "prefs.latex": "Formulas (LaTeX Suite)",
      "prefs.latexSnippets": "Snippets",
      "prefs.latexSnippets.hint": "“sr” becomes ^{2}, “@a” \\alpha, “dint” an integral; Tab goes to the next place to fill in. Your own: ~/.config/mdview/snippets.js.",
      "prefs.latexFraction": "Fraction with “/”",
      "prefs.latexFraction.hint": "What stands before the “/” becomes the numerator.",
      "prefs.latexMatrix": "Matrix keys",
      "prefs.latexMatrix.hint": "In a matrix, cases or align: Tab writes “&”, Enter “\\\\” and a new line, Shift+Enter leaves it.",
      "prefs.latexTabout": "Tab leaves brackets",
      "prefs.latexTabout.hint": "Tab goes behind the next closing bracket; at the end, out of the formula.",
      "prefs.latexEnlarge": "Brackets grow",
      "prefs.latexEnlarge.hint": "Brackets around a sum, an integral or a fraction become \\left … \\right.",
      "prefs.latexBrackets": "Matching brackets in one colour",
      "prefs.latexText": "“mk” and “dm” in the text",
      "prefs.latexText.hint": "Typed as a word: “mk” starts a formula in the line, “dm” one on its own lines.",
      "dialog.box": "Box",
      "prefs.lang": "Language",
      "prefs.lang.hint": "Of the settings, and of the active mode's menus and dialogs. Takes effect in new windows.",
      "prefs.startMode": "A new window opens in",
      "prefs.start.last": "The mode used last",
      "prefs.bar": "Formatting bar over a selection",
      "prefs.slash": "Insert menu with “/”",
      "prefs.slash.hint": "A “/” at the start of an empty line opens it.",
      "prefs.syntax": "Show Markdown at the caret",
      "prefs.syntax.hint": "The marks of bold, italic, code, links and headings show where the caret is.",
      "prefs.quotes": "Typographic quotes while typing",
      "prefs.wrap": "Wrap new paragraphs at",
      "prefs.wrap.off": "Don't wrap",
      "prefs.wrap.hint": "Only paragraphs that are written anew; the others stay as they are.",
      "prefs.images": "Pasted and dropped pictures go",
      "prefs.images.beside": "Beside the note",
      "prefs.images.assets": "Into ./assets",
      "prefs.style": "Style for new elements",
      "prefs.style.auto": "As the document does it",
      "prefs.style.fixed": "Always as set here",
      "prefs.bullet": "Bullets",
      "prefs.ordered": "Numbers",
      "prefs.emphasis": "Italic",
      "prefs.strongMark": "Bold",
      "prefs.langLater": "The language changes in new windows",
      "menu.image": "Picture",
      "menu.graphic": "Graphic by Claude…",
      "graphic.title": "Graphic",
      "graphic.describe": "Describe what to draw — a circuit, a logic diagram, a block or RTL diagram, a scheme …",
      "graphic.reference": "Reference picture",
      "graphic.choose": "Choose…",
      "graphic.paste": "Paste",
      "graphic.remove": "Remove",
      "graphic.draw": "Draw",
      "graphic.again": "Draw again",
      "graphic.stop": "Stop",
      "graphic.change": "What to change …",
      "graphic.apply": "Change",
      "graphic.insert": "Insert",
      "graphic.empty": "The figure shows here.",
      "graphic.drawing": "Drawing … {0} s",
      "graphic.failed": "No figure came back",
      "graphic.hint": "Drawn by Claude (the claude command). Description and reference picture are sent to Anthropic.",
      "menu.none": "Nothing found",
      "panel.label": "Insert and format",
      "panel.insert": "Insert",
      "panel.format": "Format",
      "panel.hint": "Click an item, or drag it into the document",
      "panel.search": "Search",
      "panel.blocks": "Blocks",
      "panel.lists": "Lists",
      "panel.separators": "Separators",
      "panel.media": "Media",
      "panel.mermaid": "Mermaid",
      "panel.graphic": "Graphic",
      "panel.both": "Block + Focus",
      "panel.titles": "Titles",
      "panel.content": "Content",
      "panel.outdent": "Decrease Indent",
      "panel.indent": "Increase Indent",
      "slash.columns": "Columns",
      "columns.n": "{0} Columns",
      "columns.addLeft": "Add Column Left",
      "columns.addRight": "Add Column Right",
      "columns.moveLeft": "Move Column Left",
      "columns.moveRight": "Move Column Right",
      "columns.equal": "Equal Widths",
      "columns.unwrap": "Unwrap Columns",
      "columns.remove": "Remove Column",
      "columns.delete": "Delete Columns",
      "slash.style": "Text Style",
      "slash.list": "List",
      "slash.actions": "Actions",
      "slash.deco": "Decorations",
      "slash.block": "Block",
      "slash.focus": "Focus",
      "slash.color": "Color",
      "slash.callout": "Callout",
      "callout.title": "Edit Title",
      "callout.note": "Note",
      "callout.info": "Info",
      "callout.tip": "Tip",
      "callout.success": "Success",
      "callout.question": "Question",
      "callout.warning": "Warning",
      "callout.error": "Error",
      "callout.bug": "Bug",
      "callout.example": "Example",
      "callout.important": "Important",
      "slash.colorDefault": "Default",
      "color.red": "Red",
      "color.orange": "Orange",
      "color.yellow": "Yellow",
      "color.green": "Green",
      "color.cyan": "Cyan",
      "color.blue": "Blue",
      "color.magenta": "Magenta",
      "slash.duplicate": "Duplicate",
      "slash.moveUp": "Move Up",
      "slash.moveDown": "Move Down",
      "slash.select": "Select Block",
      "slash.delete": "Delete Block",
      "slash.check": "Mark as Done",
      "slash.uncheck": "Mark as Not Done",
      "dialog.mathShape": "Shape of the formula",
      "dialog.block": "Block",
      "dialog.inline": "In the line",
      "dialog.copyLatex": "Copy LaTeX",
      "dialog.copyPicture": "Copy as Picture",
      "dialog.pictureCopied": "The formula is on the clipboard as a picture",
      "dialog.restore": "Restore Discarded Changes",
      "dialog.form": "Form",
      "dialog.asYaml": "Nested — edit as YAML",
      "dialog.addProperty": "Add Property",
      "dialog.removeProperty": "Remove property",
      "dialog.propertyName": "Name",
      "dialog.propertyValue": "Value",
      "dialog.find": "Find",
      "dialog.found": "{0} of {1}",
      "island.hint": "{0}, {1} lines. Press Enter to edit.",
      "dialog.cancel": "Cancel",
      "dialog.done": "Done",
      "dialog.copy": "Copy",
      "dialog.copied": "Copied",
      "dialog.count": "{0} lines · {1} characters",
      "dialog.code": "Code block",
      "dialog.language": "Language",
      "dialog.nolang": "No language",
      "dialog.info": "More info",
      "dialog.math": "Formula",
      "dialog.blanklines": "Blank lines can break the formula in some Markdown programs.",
      "dialog.remove": "Remove",
      "dialog.frontmatter": "Properties",
      "dialog.html": "HTML",
      "dialog.table": "Table",
      "dialog.deflist": "Definition list",
      "dialog.callout": "Callout",
      "dialog.markdown": "Markdown",
      "dialog.wikilink": "Wikilink",
      "dialog.note": "Note",
      "dialog.image": "Picture",
      "dialog.alt": "Description",
      "dialog.imgtitle": "Title",
      "active.keptEdits": "File changed on disk — keeping your edits",
    },
    de: {
      "mode.label": "Modus",
      "mode.edit": "Quelltext bearbeiten",
      "mode.active": "Aktiv",
      "mode.read": "Lesen",
      "mode.tip.edit": "{0} (Strg+Alt+1 oder Strg+E)",
      "mode.tip.active": "{0} (Strg+Alt+2)",
      "mode.tip.read": "{0} (Strg+Alt+3)",
      "active.loadFailed": "Aktiv-Modus konnte nicht geladen werden",
      "active.placeholder": "Schreib los …",
      "active.label": "Dokument",
      "link.label": "Link",
      "link.open": "Öffnen",
      "link.edit": "Bearbeiten",
      "link.remove": "Entfernen",
      "link.text": "Text",
      "link.url": "Adresse",
      "table.rowAbove": "Zeile darüber einfügen",
      "table.rowBelow": "Zeile darunter einfügen",
      "table.rowUp": "Zeile nach oben bewegen",
      "table.rowDown": "Zeile nach unten bewegen",
      "table.rowDelete": "Zeile löschen",
      "table.colLeft": "Spalte links einfügen",
      "table.colRight": "Spalte rechts einfügen",
      "table.colMoveLeft": "Spalte nach links bewegen",
      "table.colMoveRight": "Spalte nach rechts bewegen",
      "table.align.left": "Linksbündig",
      "table.align.center": "Zentriert",
      "table.align.right": "Rechtsbündig",
      "table.colDelete": "Spalte löschen",
      "table.delete": "Tabelle löschen",
      "table.wide": "Volle Breite",
      "table.column": "Spalte",
      "table.row": "Zeile",
      "dialog.footnote": "Fußnote {0}",
      "menu.cut": "Ausschneiden",
      "menu.copy": "Kopieren",
      "menu.paste": "Einfügen",
      "menu.pastePlain": "Einsetzen und Stil anpassen",
      "menu.link": "Link hinzufügen …",
      "menu.editLink": "Link bearbeiten …",
      "menu.openLink": "Link öffnen",
      "menu.format": "Format",
      "menu.bold": "Fett",
      "menu.italic": "Kursiv",
      "menu.strike": "Durchgestrichen",
      "menu.code": "Code",
      "menu.math": "Formel aus Auswahl",
      "menu.paragraph": "Absatz",
      "menu.text": "Text",
      "menu.heading": "Überschrift {0}",
      "menu.bullet": "Aufzählung",
      "menu.ordered": "Nummerierte Liste",
      "menu.task": "Aufgabenliste",
      "menu.quote": "Zitat",
      "menu.insert": "Einfügen",
      "menu.codeBlock": "Codeblock",
      "menu.formula": "Formel",
      "menu.table": "Tabelle",
      "menu.rule": "Trennlinie",
      "menu.footnote": "Fußnote",
      "menu.edit": "Bearbeiten …",
      "menu.copyMarkdown": "Als Markdown kopieren",
      "menu.delete": "Löschen",
      "bar.label": "Formatierung",
      "bar.bold": "Fett",
      "bar.italic": "Kursiv",
      "bar.strike": "Durchgestrichen",
      "bar.code": "Code",
      "bar.link": "Link",
      "bar.math": "Formel",
      "bar.paragraph": "Absatz",
      "ask.title": "Änderungen in diesem Dialog übernehmen?",
      "ask.text": "Deine Eingaben hier sind noch nicht Teil des Dokuments.",
      "ask.apply": "Übernehmen",
      "ask.discard": "Verwerfen",
      "island.code": "{0}, {1} Zeilen. Eingabetaste zum Bearbeiten.",
      "island.code1": "{0}, eine Zeile. Eingabetaste zum Bearbeiten.",
      "island.math": "Formel: {0}. Eingabetaste zum Bearbeiten.",
      "dialog.gone": "Der Block ist nicht mehr in der Datei — dein Text liegt in der Zwischenablage",
      "active.large": "Großes Dokument — der Aktiv-Modus kann langsamer sein",
      "prefs.title": "Einstellungen",
      "prefs.open": "Einstellungen …",
      "prefs.general": "Allgemein",
      "prefs.editing": "Bearbeiten im Aktiv-Modus",
      "prefs.newMarkdown": "Neues Markdown",
      "prefs.page.general": "Allgemein",
      "prefs.page.appearance": "Darstellung",
      "prefs.page.sidebarPage": "Seitenleiste",
      "prefs.page.allNotes": "Alle Notizen",
      "prefs.page.editing": "Bearbeiten",
      "prefs.page.newMarkdown": "Neues Markdown",
      "prefs.page.latex": "Formeln",
      "prefs.page.pdf": "PDFs",
      "prefs.page.ai": "Schreibhilfe",
      "prefs.page.about": "Über",
      "prefs.group.notes": "Notizen",
      "prefs.group.writing": "Schreiben",
      "prefs.close": "Schließen",
      "prefs.docZoom": "Textgröße einer Notiz",
      "prefs.docZoom.hint": "Auch Ctrl oder Super mit + und −; Ctrl+0 für 100 %. Nur die Notiz wird skaliert, nicht die App darum.",
      "prefs.measure": "Breite der Textspalte",
      "prefs.measure.narrow": "Schmal",
      "prefs.measure.normal": "Normal",
      "prefs.measure.wide": "Breit",
      "prefs.measure.full": "So breit wie das Fenster",
      "prefs.hinting": "Schärferer Text",
      "prefs.hinting.hint": "Buchstaben werden auf ganze Pixel gesetzt: schärfer auf einem Bildschirm gewöhnlicher Auflösung, ihre Formen leicht verändert. Gilt ab dem nächsten Start der App.",
      "prefs.restartLater": "Gilt ab dem nächsten Start der App",
      "prefs.ovScope": "Zeigen",
      "prefs.ovScope.all": "Alle Notizen, nach Ordner",
      "prefs.ovScope.folders": "Einen Ordner nach dem anderen",
      "prefs.ovLayout": "Als",
      "prefs.ovLayout.tiles": "Kacheln",
      "prefs.ovLayout.list": "Liste",
      "prefs.paragraphs": "Absätze",
      "prefs.pictures": "Bilder",
      "prefs.pdfFormat": "Ein Link auf markierten Text wird kopiert als",
      "prefs.pdfFormat.callout": "Zitat in einem Callout",
      "prefs.pdfFormat.quote": "Zitat",
      "prefs.pdfFormat.link": "Link",
      "prefs.pdfFormat.embed": "Einbettung",
      "prefs.pdfAuto": "Kopieren, sobald Text markiert ist",
      "prefs.aiKeySection": "Gemini",
      "prefs.aiKey": "API-Schlüssel",
      "prefs.aiKey.hint": "Liegt in ~/.config/mdview/.env, nur für dich lesbar. Der Text um die Schreibmarke geht an Google, wenn ein Vorschlag angefragt wird.",
      "prefs.aiKey.placeholder": "Schlüssel einfügen",
      "prefs.aiKey.save": "Sichern",
      "prefs.aiKey.remove": "Entfernen",
      "prefs.aiKey.none": "Kein Schlüssel",
      "prefs.aiKey.set": "Schlüssel endet auf %s",
      "prefs.aiKey.env": "Aus der Umgebung (GEMINI_API_KEY)",
      "prefs.aiModel": "Modell",
      "prefs.aiModel.hint": "Leer gelassen, wird die Wahl der App gefragt.",
      "prefs.version": "Version",
      "prefs.guide": "Alles, was die App kann",
      "prefs.guide.do": "Anleitung öffnen",
      "prefs.configDir": "Einstellungsordner",
      "prefs.sidebarSort": "Notizen sortieren nach",
      "prefs.sort.opened": "Zuletzt geöffnet",
      "prefs.sort.name": "Name",
      "prefs.sort.modified": "Änderungsdatum",
      "prefs.sidebar": "Seitenleiste zeigt neben Notizen",
      "prefs.sidebarPdf": "PDFs",
      "prefs.sidebarImages": "Bilder",
      "prefs.sidebarMedia": "Ton und Video",
      "prefs.sidebarOther": "Alle anderen Dateien",
      "prefs.sidebarOther.hint": "Bilder, Ton, Video und andere Dateien öffnen sich in ihrem eigenen Programm.",
      "prefs.ai": "Schreibhilfe",
      "prefs.aiComplete": "Beim Tippen die nächsten Wörter vorschlagen",
      "prefs.aiComplete.hint": "In einer Pause erscheint eine Fortsetzung in Grau: Tab übernimmt sie, Ctrl+→ das nächste Wort, Esc verwirft sie. Braucht einen Schlüssel für Gemini (unten).",
      "prefs.latex": "Formeln (LaTeX Suite)",
      "prefs.latexSnippets": "Snippets",
      "prefs.latexSnippets.hint": "„sr“ wird ^{2}, „@a“ \\alpha, „dint“ ein Integral; Tab springt zur nächsten Stelle. Eigene: ~/.config/mdview/snippets.js.",
      "prefs.latexFraction": "Bruch mit „/“",
      "prefs.latexFraction.hint": "Was vor dem „/“ steht, wird der Zähler.",
      "prefs.latexMatrix": "Matrix-Tasten",
      "prefs.latexMatrix.hint": "In matrix, cases oder align: Tab schreibt „&“, Enter „\\\\“ und eine neue Zeile, Shift+Enter verlässt sie.",
      "prefs.latexTabout": "Tab verlässt Klammern",
      "prefs.latexTabout.hint": "Tab springt hinter die nächste schließende Klammer; am Ende aus der Formel.",
      "prefs.latexEnlarge": "Klammern wachsen",
      "prefs.latexEnlarge.hint": "Klammern um Summe, Integral oder Bruch werden \\left … \\right.",
      "prefs.latexBrackets": "Klammerpaare in einer Farbe",
      "prefs.latexText": "„mk“ und „dm“ im Text",
      "prefs.latexText.hint": "Als eigenes Wort getippt: „mk“ beginnt eine Formel in der Zeile, „dm“ eine abgesetzte.",
      "dialog.box": "Einrahmen",
      "prefs.lang": "Sprache",
      "prefs.lang.hint": "Der Einstellungen sowie der Menüs und Dialoge des Aktiv-Modus. Gilt für neue Fenster.",
      "prefs.startMode": "Ein neues Fenster öffnet",
      "prefs.start.last": "Im zuletzt benutzten Modus",
      "prefs.bar": "Formatierungsleiste über einer Auswahl",
      "prefs.slash": "Einfügen-Menü mit „/“",
      "prefs.slash.hint": "Ein „/“ am Anfang einer leeren Zeile öffnet es.",
      "prefs.syntax": "Markdown beim Cursor zeigen",
      "prefs.syntax.hint": "Die Zeichen von Fett, Kursiv, Code, Links und Überschriften zeigen sich dort, wo der Cursor steht.",
      "prefs.quotes": "Typografische Anführungszeichen beim Tippen",
      "prefs.wrap": "Neue Absätze umbrechen bei",
      "prefs.wrap.off": "Nicht umbrechen",
      "prefs.wrap.hint": "Nur Absätze, die neu geschrieben werden; die anderen bleiben, wie sie sind.",
      "prefs.images": "Eingefügte und abgelegte Bilder",
      "prefs.images.beside": "Neben die Notiz",
      "prefs.images.assets": "In ./assets",
      "prefs.style": "Stil für neue Elemente",
      "prefs.style.auto": "Wie im Dokument",
      "prefs.style.fixed": "Immer wie hier eingestellt",
      "prefs.bullet": "Aufzählung",
      "prefs.ordered": "Nummern",
      "prefs.emphasis": "Kursiv",
      "prefs.strongMark": "Fett",
      "prefs.langLater": "Die Sprache ändert sich in neuen Fenstern",
      "menu.image": "Bild",
      "menu.graphic": "Grafik von Claude …",
      "graphic.title": "Grafik",
      "graphic.describe": "Beschreib, was gezeichnet werden soll – eine Schaltung, ein Logikdiagramm, ein Block- oder RTL-Diagramm, ein Schema …",
      "graphic.reference": "Referenzbild",
      "graphic.choose": "Wählen …",
      "graphic.paste": "Einfügen",
      "graphic.remove": "Entfernen",
      "graphic.draw": "Zeichnen",
      "graphic.again": "Neu zeichnen",
      "graphic.stop": "Stopp",
      "graphic.change": "Was soll sich ändern …",
      "graphic.apply": "Ändern",
      "graphic.insert": "Einfügen",
      "graphic.empty": "Hier erscheint die Grafik.",
      "graphic.drawing": "Zeichne … {0} s",
      "graphic.failed": "Es kam keine Grafik zurück",
      "graphic.hint": "Gezeichnet von Claude (Befehl claude). Beschreibung und Referenzbild gehen an Anthropic.",
      "menu.none": "Nichts gefunden",
      "panel.label": "Einfügen und formatieren",
      "panel.insert": "Einfügen",
      "panel.format": "Format",
      "panel.hint": "Auf ein Element klicken oder es ins Dokument ziehen",
      "panel.search": "Suchen",
      "panel.blocks": "Blöcke",
      "panel.lists": "Listen",
      "panel.separators": "Trennlinien",
      "panel.media": "Medien",
      "panel.mermaid": "Mermaid",
      "panel.graphic": "Grafik",
      "panel.both": "Block + Fokus",
      "panel.titles": "Titel",
      "panel.content": "Inhalt",
      "panel.outdent": "Einzug verkleinern",
      "panel.indent": "Einzug vergrößern",
      "slash.columns": "Spalten",
      "columns.n": "{0} Spalten",
      "columns.addLeft": "Spalte links hinzufügen",
      "columns.addRight": "Spalte rechts hinzufügen",
      "columns.moveLeft": "Spalte nach links bewegen",
      "columns.moveRight": "Spalte nach rechts bewegen",
      "columns.equal": "Gleiche Breiten",
      "columns.unwrap": "Spalten auflösen",
      "columns.remove": "Spalte entfernen",
      "columns.delete": "Spalten löschen",
      "slash.style": "Textstil",
      "slash.list": "Liste",
      "slash.actions": "Aktionen",
      "slash.deco": "Dekorationen",
      "slash.block": "Block",
      "slash.focus": "Fokus",
      "slash.color": "Farbe",
      "slash.callout": "Hinweisbox",
      "callout.title": "Titel bearbeiten",
      "callout.note": "Notiz",
      "callout.info": "Info",
      "callout.tip": "Tipp",
      "callout.success": "Erfolg",
      "callout.question": "Frage",
      "callout.warning": "Warnung",
      "callout.error": "Fehler",
      "callout.bug": "Bug",
      "callout.example": "Beispiel",
      "callout.important": "Wichtig",
      "slash.colorDefault": "Standard",
      "color.red": "Rot",
      "color.orange": "Orange",
      "color.yellow": "Gelb",
      "color.green": "Grün",
      "color.cyan": "Cyan",
      "color.blue": "Blau",
      "color.magenta": "Magenta",
      "slash.duplicate": "Duplizieren",
      "slash.moveUp": "Nach oben bewegen",
      "slash.moveDown": "Nach unten bewegen",
      "slash.select": "Block auswählen",
      "slash.delete": "Block löschen",
      "slash.check": "Als erledigt markieren",
      "slash.uncheck": "Als offen markieren",
      "dialog.mathShape": "Form der Formel",
      "dialog.block": "Block",
      "dialog.inline": "In der Zeile",
      "dialog.copyLatex": "LaTeX kopieren",
      "dialog.copyPicture": "Als Bild kopieren",
      "dialog.pictureCopied": "Die Formel liegt als Bild in der Zwischenablage",
      "dialog.restore": "Verworfenes wiederherstellen",
      "dialog.form": "Formular",
      "dialog.asYaml": "Verschachtelt — als YAML bearbeiten",
      "dialog.addProperty": "Eigenschaft hinzufügen",
      "dialog.removeProperty": "Eigenschaft entfernen",
      "dialog.propertyName": "Name",
      "dialog.propertyValue": "Wert",
      "dialog.find": "Suchen",
      "dialog.found": "{0} von {1}",
      "island.hint": "{0}, {1} Zeilen. Eingabetaste zum Bearbeiten.",
      "dialog.cancel": "Abbrechen",
      "dialog.done": "Fertig",
      "dialog.copy": "Kopieren",
      "dialog.copied": "Kopiert",
      "dialog.count": "{0} Zeilen · {1} Zeichen",
      "dialog.code": "Codeblock",
      "dialog.language": "Sprache",
      "dialog.nolang": "Keine Sprache",
      "dialog.info": "Weitere Info",
      "dialog.math": "Formel",
      "dialog.blanklines": "Leerzeilen können in manchen Markdown-Programmen die Formel brechen.",
      "dialog.remove": "Entfernen",
      "dialog.frontmatter": "Eigenschaften",
      "dialog.html": "HTML",
      "dialog.table": "Tabelle",
      "dialog.deflist": "Definitionsliste",
      "dialog.callout": "Callout",
      "dialog.markdown": "Markdown",
      "dialog.wikilink": "Wikilink",
      "dialog.note": "Notiz",
      "dialog.image": "Bild",
      "dialog.alt": "Beschreibung",
      "dialog.imgtitle": "Titel",
      "active.keptEdits": "Datei wurde außerhalb geändert — deine Änderungen bleiben",
    },
  };
  const S = {
    lang: /^(en|de)$/.test((window.MdPrefs || {}).lang) ? window.MdPrefs.lang : "en", // (settings: a new window takes another)
    t(key, ...values) {
      const s = (TABLES[S.lang] && TABLES[S.lang][key]) ?? TABLES.en[key] ?? key;
      return s.replace(/\{(\d+)\}/g, (_m, i) => values[i] ?? "");
    },
  };
  window.MdStrings = S;
})();
