/* mdview — user-facing strings of the active mode, in one place so they can
 * be translated. MdStrings.t("key", …values) fills {0}, {1} …
 * The app's older strings are still inline in viewer.js and mdview.py. */
"use strict";
(() => {
  const TABLES = {
    en: {
      "mode.label": "Mode",
      "mode.edit": "Edit source",
      "mode.active": "Active",
      "mode.read": "Read",
      "mode.tip.edit": "{0} (Ctrl+Alt+1, or Ctrl+E)",
      "mode.tip.active": "{0} (Ctrl+Alt+2)",
      "mode.tip.read": "{0} (Ctrl+Alt+3)",
      "active.loadFailed": "Couldn't load the active mode",
      "share.title": "Share “{0}”",
      "share.intro": "Anyone with the link can read this note, with its pictures and what it embeds — and nothing else of the folder.",
      "share.on": "Anyone with the link can read this note.",
      "share.on.password": "Anyone with the link and the password can read this note.",
      "share.pending": "The link works once this is sent to GitHub.",
      "share.cannot": "This note cannot be shared from here.",
      "share.silent": "The app did not answer. Quit it and start it again: it was started before it could share.",
      "share.link": "Link",
      "share.copy": "Copy Link",
      "share.raw": "Link to the Markdown",
      "share.copyRaw": "Copy Raw Link",
      "share.copied": "Copied",
      "share.password": "Password",
      "share.password.none": "None",
      "share.password.is": "Set",
      "share.password.will": "With Share",
      "share.password.hint": "Asked for before the note is shown.",
      "share.password.new": "New password",
      "share.password.set": "Set Password",
      "share.password.change": "Change",
      "share.password.remove": "Remove Password",
      "share.start": "Share",
      "share.need.history": "Sharing needs this folder’s history, and a link to GitHub.",
      "share.need.link": "Sharing needs a link to a repository on GitHub.",
      "share.fix.history": "Turn On History…",
      "share.fix.link": "Open Settings…",
      "share.stop": "Stop Sharing",
      "share.download": "Download",
      "share.download.name": "Download",
      "share.download.what": "The note, as a Markdown file",
      "history.title": "History",
      "history.versions": "Versions",
      "history.close": "Close",
      "history.loading": "Loading",
      "history.compare": "Compare",
      "history.mode.change": "What this version changed",
      "history.mode.now": "Difference to the note now",
      "history.restore": "Restore This Version",
      "history.restored": "The version of {0} is the note again",
      "history.same": "No difference",
      "history.unchanged": "{0} lines unchanged",
      "history.unchanged.one": "1 line unchanged",
      "history.none": "No version of this note has been kept yet",
      "history.off": "The history of this folder is off",
      "conflict.title": "Conflicts",
      "conflict.files": "Files",
      "conflict.with": "Changed here and on {0}, in the same place. Say for each how it is to be.",
      "conflict.mine": "Mine",
      "conflict.theirs": "Theirs",
      "conflict.both": "Both",
      "conflict.here": "This device · {0}",
      "conflict.there": "{0} · {1}",
      "conflict.place": "Place {0} of {1}",
      "conflict.whole": "The whole file",
      "conflict.changed": "Changed",
      "conflict.deleted": "Deleted",
      "conflict.nothing": "nothing here",
      "conflict.left": "{0} places to choose",
      "conflict.left.one": "1 place to choose",
      "conflict.done": "Chosen",
      "conflict.join": "Join",
      "conflict.joined": "Joined. Both devices have the same again",
      "active.placeholder": "Start writing…",
      "active.label": "Document",
      "link.label": "Link",
      "link.open": "Open",
      "link.edit": "Edit",
      "link.remove": "Remove",
      "link.text": "Text",
      "link.pickNote": "Name of a note",
      "link.toNew": "Link to “{0}”",
      "link.file": "File",
      "link.url": "Address",
      "table.rowAbove": "Insert Row Above",
      "table.rowBelow": "Insert Row Below",
      "table.rowUp": "Move Row Up",
      "table.rowDown": "Move Row Down",
      "table.rowDelete": "Delete Row",
      "table.colLeft": "Insert Column Left",
      "table.colRight": "Insert Column Right",
      "table.colMoveLeft": "Move Column Left",
      "table.colMoveRight": "Move Column Right",
      "table.align.left": "Align Left",
      "table.align.center": "Align Center",
      "table.align.right": "Align Right",
      "table.colDelete": "Delete Column",
      "table.delete": "Delete Table",
      "table.wide": "Full Width",
      "table.head": "Header Color",
      "table.head.none": "None",
      "table.head.own": "Custom",
      "table.head.hex": "Color",
      "table.head.bad": "Not a color: write it as #rrggbb",
      "table.menu": "Table",
      "table.column": "Column",
      "table.row": "Row",
      "dialog.footnote": "Footnote {0}",
      "menu.hideCode": "Hide the Code",
      "menu.propsHide": "Hide Properties",
      "menu.propsShow": "Show Properties",
      "menu.propsEdit": "Edit Properties…",
      "dialog.hide": "Hide",
      "dialog.hideTitle": "Title (optional)",
      "file.small": "Small",
      "file.medium": "Medium",
      "file.large": "Large",
      "menu.embedFile": "Embed in the Note",
      "menu.asFile": "Show as File",
      "menu.asPicture": "Show as Picture",
      "menu.showLarge": "Show Large",
      "menu.embedCode": "Show as Code",
      "menu.cut": "Cut",
      "menu.copy": "Copy",
      "menu.paste": "Paste",
      "menu.pastePlain": "Paste and Match Style",
      "menu.selectAll": "Select All",
      "menu.link": "Add Link…",
      "menu.editLink": "Edit Link…",
      "menu.openLink": "Open Link",
      "menu.format": "Format",
      "menu.bold": "Bold",
      "menu.italic": "Italic",
      "menu.strike": "Strikethrough",
      "menu.code": "Code",
      "menu.math": "Formula from Selection",
      "menu.paragraph": "Paragraph",
      "menu.text": "Text",
      "menu.heading": "Heading {0}",
      "menu.bullet": "Bulleted List",
      "menu.ordered": "Numbered List",
      "menu.task": "Task List",
      "menu.quote": "Quote",
      "menu.insert": "Insert",
      "menu.codeBlock": "Code Block",
      "menu.formula": "Formula",
      "menu.table": "Table",
      "menu.rule": "Divider",
      "menu.footnote": "Footnote",
      "menu.page": "Page",
      "menu.board": "Whiteboard",
      "board.name": "Whiteboard", "board.back": "Back to the Note", "board.undo": "Undo", "board.redo": "Redo", "board.tools": "Drawing tools", "board.color": "Colour",
      "board.modes": "Tools", "board.kind.lasso": "Lasso: Choose and Move", "board.kind.pen": "Pens", "board.kind.eraser": "Eraser", "board.kind.text": "Text", "board.kind.shape": "Shapes", "board.insert.image": "Picture", "board.insert.more": "More to Add", "board.form.auto": "Drawn by Hand, Made Clean",
      "board.tray.min": "Shrink the Tools", "board.tray.max": "Show the Tools", "board.tool.select": "Pointer", "board.tool.pen": "Pen", "board.tool.mono": "Fineliner", "board.tool.marker": "Marker", "board.tool.pencil": "Pencil", "board.tool.ruler": "Ruler", "board.tool.eraser": "Eraser", "board.tool.lasso": "Lasso",
      "board.options": "Tool options", "board.width": "Width", "board.opacity": "Opacity", "board.eraser.object": "Strokes", "board.eraser.pixel": "Parts",
      "board.duplicate": "Duplicate", "board.delete": "Delete", "board.ink.any": "Another colour",
      "board.insert": "Add to the board", "board.mode.draw": "Drawing Tools", "board.insert.text": "Text Box", "board.insert.shape": "Shape", "board.insert.sticky": "Sticky Note", "board.insert.table": "Table", "board.table": "Table", "board.rows": "Rows", "board.columns": "Columns", "board.header": "Header Row",
      "board.shape.rect": "Rectangle", "board.shape.round": "Rounded Rectangle", "board.shape.ellipse": "Ellipse", "board.shape.triangle": "Triangle", "board.shape.diamond": "Diamond", "board.shape.star": "Star", "board.shape.hexagon": "Hexagon", "board.shape.line": "Line", "board.shape.arrow": "Arrow",
      "board.fill": "Fill", "board.stroke": "Border", "board.textLook": "Text", "board.ends": "Line Ends", "board.arrange": "Arrange", "board.noFill": "No Fill", "board.noStroke": "No Border",
      "board.smaller": "Smaller", "board.larger": "Larger", "board.startArrow": "Arrow at the Start", "board.endArrow": "Arrow at the End",
      "board.align": "Align", "board.align.L": "Left", "board.align.C": "Centre", "board.align.R": "Right", "board.align.T": "Top", "board.align.M": "Middle", "board.align.B": "Bottom",
      "board.more": "More", "board.zoom": "Size", "board.scenes": "Scenes", "board.scene": "Scene", "board.scene.n": "Scene {0}", "board.scene.prev": "Scene Before", "board.scene.next": "Next Scene", "board.scene.add": "Add Scene", "board.scene.none": "No scenes yet. A scene keeps what the window shows now, under a name.", "board.scene.rename": "Rename", "board.scene.replace": "Replace with This View",
      "board.pen.finger": "Draw with Finger", "board.pen.selects": "Pen Selects and Scrolls", "board.copyPicture": "Copy as Picture", "board.print": "Print…", "board.snap": "Snap to Grid", "board.copied": "Copied", "board.notCopied": "Couldn't copy the picture", "board.distribute.H": "Distribute Side by Side", "board.distribute.V": "Distribute Top to Bottom",
      "board.connect": "Connectors", "board.route": "Line", "board.link": "Add Connection Line", "board.insert.link": "Link", "board.link.add": "Add Link", "board.open": "Open", "board.crop": "Crop", "board.uncrop": "Show the Whole Picture", "board.insertStyle": "Use as Style for New Ones", "board.copyStyle": "Copy Style", "board.pasteStyle": "Paste Style", "board.group": "Group", "board.ungroup": "Ungroup", "board.front": "Bring to Front", "board.toBack": "Send to Back", "board.lock": "Lock", "board.unlock": "Unlock",
      "board.ink.auto": "Black", "board.ink.blue": "Blue", "board.ink.green": "Green", "board.ink.yellow": "Yellow", "board.ink.red": "Red", "board.ink.purple": "Purple",
      "board.actual": "Actual Size", "board.fit": "Show Everything", "board.grid": "Dot Grid",
      "board.notSaved": "Not saved", "board.lost": "{0} items could not be read", "board.cantOpen": "Couldn't open the whiteboard", "board.noPicture": "Couldn't put the picture on the board",
      "menu.pageOpen": "Open Page",
      "menu.pageRename": "Rename",
      "page.name": "Name",
      "menu.pageStyle": "Style",
      "page.style.row": "Row",
      "page.style.card": "Card",
      "link.style.inline": "In Text",
      "new.note": "New Note",
      "empty.title": "No Notes Yet",
      "toast.undo": "Undo",
      "active.cannotSay": "Markdown cannot write part of this the way it is shown: it is saved in its plain form",
      "empty.text": "Notes are plain Markdown files in this folder.",
      "new.folder": "New Folder",
      "new.in": "In “{0}”",
      "new.create": "Create",
      "new.quickHint": "Without a name, it is named after its first line.",
      "menu.noteOpen": "Open Note",
      "page.untitled": "Untitled",
      "menu.edit": "Edit…",
      "menu.copyMarkdown": "Copy as Markdown",
      "menu.delete": "Delete",
      "bar.label": "Formatting",
      "bar.bold": "Bold",
      "bar.italic": "Italic",
      "bar.strike": "Strikethrough",
      "bar.code": "Code",
      "bar.link": "Link",
      "bar.math": "Formula",
      "bar.paragraph": "Paragraph",
      "ask.title": "Apply the changes in this dialog?",
      "ask.text": "Your edits here are not part of the document yet.",
      "ask.apply": "Apply",
      "ask.discard": "Discard",
      "island.code": "{0}, {1} lines. Press Enter to edit.",
      "island.code1": "{0}, one line. Press Enter to edit.",
      "island.math": "Formula: {0}. Press Enter to edit.",
      "dialog.gone": "The block is no longer in the file — your text is on the clipboard",
      "active.large": "Large document — the active mode may be slow",
      "prefs.title": "Settings",
      "prefs.open": "Settings…",
      "prefs.general": "General",
      "prefs.editing": "Editing in the active mode",
      "prefs.newMarkdown": "New Markdown",
      "prefs.page.general": "General",
      "prefs.page.appearance": "Appearance",
      "prefs.page.sidebarPage": "Sidebar",
      "prefs.page.allNotes": "All Notes",
      "prefs.page.history": "History",
      "prefs.page.editing": "Editing",
      "prefs.page.newMarkdown": "New Markdown",
      "prefs.page.latex": "Formulas",
      "prefs.page.pdf": "PDFs",
      "prefs.page.ai": "Writing Help",
      "prefs.page.about": "About",
      "prefs.group.notes": "Notes",
      "prefs.group.writing": "Writing",
      "prefs.close": "Close",
      "prefs.docZoom": "Text size of a note",
      "prefs.docZoom.hint": "Also Ctrl or Super with + and −; Ctrl+0 for 100 %. Only the note is scaled, not the app around it.",
      "prefs.measure": "Width of the text column",
      "prefs.measure.narrow": "Narrow",
      "prefs.measure.normal": "Normal",
      "prefs.measure.wide": "Wide",
      "prefs.measure.full": "As wide as the window",
      "prefs.hinting": "Sharper text",
      "prefs.hinting.hint": "Letters are set on whole pixels: crisper on a screen of ordinary resolution, their shapes a little changed. Takes effect when the app starts next.",
      "prefs.restartLater": "Takes effect when the app starts next",
      "prefs.ovScope": "Show",
      "prefs.ovScope.all": "All notes, by folder",
      "prefs.ovScope.folders": "One folder at a time",
      "prefs.ovLayout": "As",
      "prefs.ovLayout.tiles": "Tiles",
      "prefs.ovLayout.list": "A list",
      "prefs.overview": "All Notes shows, beside notes",
      "prefs.ovPdf": "PDFs",
      "prefs.ovImages": "Pictures",
      "prefs.ovMedia": "Sound and video",
      "prefs.ovOther": "All other files",
      "prefs.ovOther.hint": "Its own choice, apart from the sidebar's. A right click in All Notes or in the sidebar has the same under Show.",
      "prefs.paragraphs": "Paragraphs",
      "prefs.pictures": "Pictures",
      "prefs.quick": "Quick Notes",
      "prefs.quickNew": "New quick note",
      "prefs.quickNew.hint": "Press the keys in the field. Backspace puts it back.",
      "prefs.quickDir": "Folder",
      "prefs.quickDir.hint": "Where quick notes are kept. Takes effect when the window is opened again.",
      "prefs.pdfFormat": "A link to selected text is copied as",
      "prefs.pdfFormat.callout": "A quote in a callout",
      "prefs.pdfFormat.quote": "A quote",
      "prefs.pdfFormat.link": "A link",
      "prefs.pdfFormat.embed": "An embed",
      "prefs.pdfAuto": "Copy as soon as text is selected",
      "prefs.aiKeySection": "Gemini",
      "prefs.aiKey": "API key",
      "prefs.aiKey.hint": "Kept in ~/.config/mdview/.env, readable by you alone. The text around the caret goes to Google when a suggestion is asked for.",
      "prefs.aiKey.placeholder": "Paste a key",
      "prefs.aiKey.save": "Save",
      "prefs.aiKey.remove": "Remove",
      "prefs.aiKey.none": "No key",
      "prefs.aiKey.set": "Key ends in %s",
      "prefs.aiKey.env": "From the environment (GEMINI_API_KEY)",
      "prefs.aiModel": "Model",
      "prefs.aiModel.hint": "Left empty, the app's own choice is asked.",
      "prefs.version": "Version",
      "prefs.guide": "Everything the app does",
      "prefs.guide.do": "Open the guide",
      "prefs.configDir": "Settings folder",
      "prefs.sidebarSort": "Sort notes by",
      "prefs.historyQuiet": "Keep changes after",
      "prefs.historyQuiet.hint": "In a folder whose history is on, what changed is kept as a version once nothing more has changed for this long — and at once when its window closes.",
      "prefs.deviceName": "Name",
      "prefs.deviceName.hint": "Every version names the device it was made on. Left empty, the computer's name.",
      "prefs.deviceId": "ID",
      "prefs.history.here": "This folder",
      "prefs.history.device": "This device",
      "prefs.history.github": "GitHub",
      "prefs.githubAccount": "Account",
      "prefs.githubAccount.hint": "For a project linked to a repository on GitHub. Only the repositories the app was given there are reached.",
      "prefs.github.none": "Not signed in",
      "prefs.github.signin": "Sign In…",
      "prefs.github.asking": "Asking GitHub…",
      "prefs.github.enter": "Confirm this code at {0}",
      "prefs.github.open": "Copy Code and Open GitHub",
      "prefs.github.cancel": "Cancel",
      "prefs.github.in": "Signed in as {0}",
      "prefs.github.out": "Sign Out",
      "prefs.github.failed": "Not signed in — {0}",
      "prefs.historyLink": "GitHub",
      "prefs.historyLink.hint": "Linked, this project and the repository are kept the same: what is kept here goes there, and what another device sent comes here.",
      "prefs.githubGet": "Get a repository",
      "prefs.githubGet.hint": "Fetched into a folder of its own, as a project linked to it.",
      "prefs.github.repo": "Repository",
      "prefs.github.search": "Search repositories",
      "prefs.github.unlinked": "Not linked",
      "prefs.github.linkTitle": "Link to a Repository",
      "prefs.github.getTitle": "Get a Repository",
      "prefs.github.linkDo": "Link",
      "prefs.github.getDo": "Get…",
      "prefs.github.private": "Private",
      "prefs.github.public": "Public",
      "prefs.github.nofit": "No repository fits",
      "prefs.github.first": "Sign in below to link",
      "prefs.github.reading": "Reading the repositories…",
      "prefs.github.norepos": "The app was given no repository",
      "prefs.github.give": "Choose on GitHub",
      "prefs.github.link": "Link…",
      "prefs.github.unlink": "Unlink",
      "prefs.github.get": "Get…",
      "prefs.sync.even": "the same on both",
      "prefs.sync.new": "linked",
      "prefs.sync.offline": "not reached — tried again later",
      "prefs.sync.signin": "sign in to go on",
      "prefs.sync.conflict": "{0} files to resolve",
      "prefs.sync.conflict.one": "1 file to resolve",
      "prefs.historyState": "History",
      "prefs.history.is.none": "Off",
      "prefs.history.is.paused": "Off — its versions are kept",
      "prefs.history.offDo": "Turn Off",
      "prefs.history.is.adopt": "Off — a Git repository is here",
      "prefs.history.is.foreign": "Kept by a repository of its own, not by this app",
      "prefs.history.is.project": "On",
      "prefs.history.is.inside": "On, as part of a project",
      "prefs.history.on": "Turn On",
      "prefs.history.adopt": "Use This Repository…",
      "prefs.historyName": "Repository",
      "prefs.historyRoot": "Folder",
      "prefs.historyBranch": "Branch",
      "prefs.history.noBranch": "None yet",
      "prefs.historyCount": "Versions",
      "prefs.historyLast": "Last version",
      "prefs.historyChanged": "Not yet kept",
      "prefs.history.allKept": "Nothing — all is kept",
      "prefs.history.waiting": "%s files, kept shortly",
      "prefs.history.changed": "%s files",
      "prefs.history.waiting.one": "1 file, kept shortly",
      "prefs.history.changed.one": "1 file",
      "prefs.sort.opened": "Last opened",
      "prefs.sort.name": "Name",
      "prefs.sort.modified": "Date modified",
      "prefs.sidebar": "Sidebar shows, beside notes",
      "prefs.sidebarPdf": "PDFs",
      "prefs.sidebarImages": "Pictures",
      "prefs.sidebarMedia": "Sound and video",
      "prefs.sidebarOther": "All other files",
      "prefs.sidebarOther.hint": "Pictures, sound, video and other files open in their own application.",
      "prefs.ai": "Writing help",
      "prefs.aiComplete": "Suggest the next words while typing",
      "prefs.aiComplete.hint": "In a pause, a continuation shows in grey: Tab takes it, Ctrl+→ the next word, Esc dismisses it. Needs a key for Gemini (below).",
      "prefs.latex": "Formulas (LaTeX Suite)",
      "prefs.latexSnippets": "Snippets",
      "prefs.latexSnippets.hint": "“sr” becomes ^{2}, “@a” \\alpha, “dint” an integral; Tab goes to the next place to fill in. Your own: ~/.config/mdview/snippets.js.",
      "prefs.latexFraction": "Fraction with “/”",
      "prefs.latexFraction.hint": "What stands before the “/” becomes the numerator.",
      "prefs.latexMatrix": "Matrix keys",
      "prefs.latexMatrix.hint": "In a matrix, cases or align: Tab writes “&”, Enter “\\\\” and a new line, Shift+Enter leaves it.",
      "prefs.latexTabout": "Tab leaves brackets",
      "prefs.latexTabout.hint": "Tab goes behind the next closing bracket; at the end, out of the formula.",
      "prefs.latexEnlarge": "Brackets grow",
      "prefs.latexEnlarge.hint": "Brackets around a sum, an integral or a fraction become \\left … \\right.",
      "prefs.latexBrackets": "Matching brackets in one colour",
      "prefs.latexText": "“mk” and “dm” in the text",
      "prefs.latexText.hint": "Typed as a word: “mk” starts a formula in the line, “dm” one on its own lines.",
      "dialog.box": "Box",
      "prefs.lang": "Language",
      "prefs.lang.hint": "Of the settings, and of the active mode's menus and dialogs. Takes effect in new windows.",
      "prefs.startMode": "A new window opens in",
      "prefs.start.last": "The mode used last",
      "prefs.bar": "Formatting bar over a selection",
      "prefs.slash": "Insert menu with “/”",
      "prefs.slash.hint": "A “/” at the start of an empty line opens it.",
      "prefs.syntax": "Show Markdown at the caret",
      "prefs.syntax.hint": "The marks of bold, italic, code, links and headings show where the caret is.",
      "prefs.quotes": "Typographic quotes while typing",
      "prefs.wrap": "Wrap new paragraphs at",
      "prefs.wrap.off": "Don't wrap",
      "prefs.wrap.hint": "Only paragraphs that are written anew; the others stay as they are.",
      "prefs.images": "Pasted and dropped pictures go",
      "prefs.images.beside": "Beside the note",
      "prefs.images.assets": "Into ./assets",
      "prefs.style": "Style for new elements",
      "prefs.style.auto": "As the document does it",
      "prefs.style.fixed": "Always as set here",
      "prefs.bullet": "Bullets",
      "prefs.ordered": "Numbers",
      "prefs.emphasis": "Italic",
      "prefs.strongMark": "Bold",
      "prefs.langLater": "The language changes in new windows",
      "menu.image": "Picture",
      "menu.file": "File",
      "menu.graphic": "Graphic by Claude…",
      "graphic.title": "Graphic",
      "graphic.describe": "Describe what to draw — a circuit, a logic diagram, a block or RTL diagram, a scheme …",
      "graphic.reference": "Reference picture",
      "graphic.choose": "Choose…",
      "graphic.paste": "Paste",
      "graphic.remove": "Remove",
      "graphic.draw": "Draw",
      "graphic.again": "Draw again",
      "graphic.stop": "Stop",
      "graphic.change": "What to change …",
      "graphic.apply": "Change",
      "graphic.insert": "Insert",
      "graphic.empty": "The figure shows here.",
      "graphic.drawing": "Drawing … {0} s",
      "graphic.failed": "No figure came back",
      "graphic.hint": "Drawn by Claude (the claude command). Description and reference picture are sent to Anthropic.",
      "menu.none": "Nothing found",
      "menu.search": "Search …",
      "panel.label": "Insert and format",
      "panel.insert": "Insert",
      "panel.format": "Format",
      "panel.hint": "Click an item, or drag it into the document",
      "panel.search": "Search",
      "panel.blocks": "Blocks",
      "panel.lists": "Lists",
      "panel.separators": "Separators",
      "panel.lines": "Insert Line",
      "panel.line.dots": "Three Dots",
      "panel.line.dotted": "Dotted Line",
      "panel.line.thin": "Thin Line",
      "panel.line.heavy": "Heavy Line",
      "panel.tableOf": "Insert Table",
      "panel.tableHint": "A table with as many rows and columns as are marked",
      "panel.tableSize": "{0} rows, {1} columns",
      "panel.media": "Media",
      "panel.mermaid": "Mermaid",
      "panel.graphic": "Graphic",
      "panel.both": "Block + Focus",
      "panel.titles": "Titles",
      "panel.text": "Text",
      "panel.groups": "Groups",
      "panel.title": "Title",
      "panel.subtitle": "Subtitle",
      "panel.heading": "Heading",
      "panel.strong": "Strong",
      "panel.body": "Body",
      "panel.content": "Content",
      "panel.outdent": "Decrease Indent",
      "panel.indent": "Increase Indent",
      "slash.columns": "Columns",
      "columns.n": "{0} Columns",
      "columns.addLeft": "Add Column Left",
      "columns.addRight": "Add Column Right",
      "columns.moveLeft": "Move Column Left",
      "columns.moveRight": "Move Column Right",
      "columns.equal": "Equal Widths",
      "columns.unwrap": "Unwrap Columns",
      "columns.remove": "Remove Column",
      "columns.delete": "Delete Columns",
      "slash.style": "Text Style",
      "slash.list": "List",
      "slash.actions": "Actions",
      "slash.deco": "Decorations",
      "slash.block": "Block",
      "slash.focus": "Focus",
      "slash.color": "Color",
      "slash.callout": "Callout",
      "callout.title": "Edit Title",
      "callout.fold": "Collapsible",
      "callout.foldOpen": "Open at First",
      "callout.note": "Note",
      "callout.info": "Info",
      "callout.tip": "Tip",
      "callout.success": "Success",
      "callout.question": "Question",
      "callout.warning": "Warning",
      "callout.error": "Error",
      "callout.bug": "Bug",
      "callout.example": "Example",
      "callout.important": "Important",
      "slash.colorDefault": "Default",
      "color.red": "Red",
      "color.orange": "Orange",
      "color.yellow": "Yellow",
      "color.green": "Green",
      "color.cyan": "Cyan",
      "color.blue": "Blue",
      "color.magenta": "Magenta",
      "slash.duplicate": "Duplicate",
      "slash.moveUp": "Move Up",
      "slash.moveDown": "Move Down",
      "slash.select": "Select Block",
      "slash.delete": "Delete Block",
      "slash.check": "Mark as Done",
      "slash.uncheck": "Mark as Not Done",
      "dialog.mathShape": "Shape of the formula",
      "dialog.block": "Block",
      "dialog.inline": "In the line",
      "dialog.copyLatex": "Copy LaTeX",
      "dialog.copyPicture": "Copy as Picture",
      "dialog.pictureCopied": "The formula is on the clipboard as a picture",
      "dialog.restore": "Restore Discarded Changes",
      "dialog.form": "Form",
      "dialog.asYaml": "Nested — edit as YAML",
      "dialog.addProperty": "Add Property",
      "dialog.removeProperty": "Remove property",
      "dialog.propertyName": "Name",
      "dialog.propertyValue": "Value",
      "dialog.find": "Find",
      "dialog.found": "{0} of {1}",
      "island.hint": "{0}, {1} lines. Press Enter to edit.",
      "dialog.cancel": "Cancel",
      "dialog.done": "Done",
      "dialog.copy": "Copy",
      "dialog.copied": "Copied",
      "dialog.count": "{0} lines · {1} characters",
      "dialog.code": "Code block",
      "dialog.language": "Language",
      "dialog.nolang": "No language",
      "dialog.info": "More info",
      "dialog.math": "Formula",
      "dialog.blanklines": "Blank lines can break the formula in some Markdown programs.",
      "dialog.remove": "Remove",
      "dialog.frontmatter": "Properties",
      "dialog.html": "HTML",
      "dialog.table": "Table",
      "dialog.deflist": "Definition list",
      "dialog.callout": "Callout",
      "dialog.markdown": "Markdown",
      "dialog.size": "Size",
      "size.auto": "Its own size",
      "size.small": "Small",
      "size.medium": "Medium",
      "size.large": "Large",
      "size.full": "Full width",
      "menu.openPdf": "Go to PDF",
      "dialog.adjust": "Adjust Region",
      "dialog.adjustDone": "Show Result",
      "dialog.adjustHint": "Pull the frame or its edges; pull anywhere else for a new one",
      "dialog.adjustPage": "Page {0} of {1}",
      "dialog.adjustPrev": "Previous page",
      "dialog.adjustNext": "Next page",
      "dialog.wikilink": "Wikilink",
      "dialog.note": "Note",
      "dialog.image": "Picture",
      "dialog.alt": "Description",
      "dialog.imgtitle": "Title",
      "active.keptEdits": "File changed on disk — keeping your edits",
    },
    de: {
      "mode.label": "Modus",
      "mode.edit": "Quelltext bearbeiten",
      "mode.active": "Aktiv",
      "mode.read": "Lesen",
      "mode.tip.edit": "{0} (Strg+Alt+1 oder Strg+E)",
      "mode.tip.active": "{0} (Strg+Alt+2)",
      "mode.tip.read": "{0} (Strg+Alt+3)",
      "active.loadFailed": "Aktiv-Modus konnte nicht geladen werden",
      "share.title": "„{0}“ teilen",
      "share.intro": "Wer den Link hat, kann diese Notiz lesen, mit ihren Bildern und dem, was sie einbettet – und sonst nichts aus dem Ordner.",
      "share.on": "Wer den Link hat, kann diese Notiz lesen.",
      "share.on.password": "Wer den Link und das Passwort hat, kann diese Notiz lesen.",
      "share.pending": "Der Link geht, sobald das bei GitHub angekommen ist.",
      "share.cannot": "Diese Notiz lässt sich von hier nicht teilen.",
      "share.silent": "Die App hat nicht geantwortet. Beende sie und starte sie neu: Sie lief schon, bevor sie teilen konnte.",
      "share.link": "Link",
      "share.copy": "Link kopieren",
      "share.raw": "Link zum Markdown",
      "share.copyRaw": "Raw-Link kopieren",
      "share.copied": "Kopiert",
      "share.password": "Passwort",
      "share.password.none": "Keines",
      "share.password.is": "Gesetzt",
      "share.password.will": "Mit dem Teilen",
      "share.password.hint": "Wird abgefragt, bevor die Notiz gezeigt wird.",
      "share.password.new": "Neues Passwort",
      "share.password.set": "Passwort setzen",
      "share.password.change": "Ändern",
      "share.password.remove": "Passwort entfernen",
      "share.start": "Teilen",
      "share.need.history": "Zum Teilen braucht dieser Ordner seinen Verlauf und eine Verbindung zu GitHub.",
      "share.need.link": "Zum Teilen braucht es eine Verbindung zu einem Repository auf GitHub.",
      "share.fix.history": "Verlauf einschalten …",
      "share.fix.link": "Einstellungen öffnen …",
      "share.stop": "Nicht mehr teilen",
      "share.download": "Herunterladen",
      "share.download.name": "Herunterladen",
      "share.download.what": "Die Notiz als Markdown-Datei",
      "history.title": "Verlauf",
      "history.versions": "Versionen",
      "history.close": "Schließen",
      "history.loading": "Lädt",
      "history.compare": "Vergleichen",
      "history.mode.change": "Was diese Version geändert hat",
      "history.mode.now": "Unterschied zur Notiz jetzt",
      "history.restore": "Diese Version wiederherstellen",
      "history.restored": "Die Version vom {0} ist wieder die Notiz",
      "history.same": "Kein Unterschied",
      "history.unchanged": "{0} Zeilen unverändert",
      "history.unchanged.one": "1 Zeile unverändert",
      "history.none": "Von dieser Notiz ist noch keine Version festgehalten",
      "history.off": "Der Verlauf dieses Ordners ist aus",
      "conflict.title": "Konflikte",
      "conflict.files": "Dateien",
      "conflict.with": "Hier und auf {0} geändert, an derselben Stelle. Sag für jede, wie es sein soll.",
      "conflict.mine": "Meine",
      "conflict.theirs": "Ihre",
      "conflict.both": "Beide",
      "conflict.here": "Dieses Gerät · {0}",
      "conflict.there": "{0} · {1}",
      "conflict.place": "Stelle {0} von {1}",
      "conflict.whole": "Die ganze Datei",
      "conflict.changed": "Geändert",
      "conflict.deleted": "Gelöscht",
      "conflict.nothing": "hier nichts",
      "conflict.left": "{0} Stellen zu wählen",
      "conflict.left.one": "1 Stelle zu wählen",
      "conflict.done": "Gewählt",
      "conflict.join": "Zusammenführen",
      "conflict.joined": "Zusammengeführt. Beide Geräte haben wieder dasselbe",
      "active.placeholder": "Schreib los …",
      "active.label": "Dokument",
      "link.label": "Link",
      "link.open": "Öffnen",
      "link.edit": "Bearbeiten",
      "link.remove": "Entfernen",
      "link.text": "Text",
      "link.pickNote": "Name einer Notiz",
      "link.toNew": "Link zu „{0}“",
      "link.file": "Datei",
      "link.url": "Adresse",
      "table.rowAbove": "Zeile darüber einfügen",
      "table.rowBelow": "Zeile darunter einfügen",
      "table.rowUp": "Zeile nach oben bewegen",
      "table.rowDown": "Zeile nach unten bewegen",
      "table.rowDelete": "Zeile löschen",
      "table.colLeft": "Spalte links einfügen",
      "table.colRight": "Spalte rechts einfügen",
      "table.colMoveLeft": "Spalte nach links bewegen",
      "table.colMoveRight": "Spalte nach rechts bewegen",
      "table.align.left": "Linksbündig",
      "table.align.center": "Zentriert",
      "table.align.right": "Rechtsbündig",
      "table.colDelete": "Spalte löschen",
      "table.delete": "Tabelle löschen",
      "table.wide": "Volle Breite",
      "table.head": "Kopffarbe",
      "table.head.none": "Keine",
      "table.head.own": "Eigene",
      "table.head.hex": "Farbe",
      "table.head.bad": "Keine Farbe: als #rrggbb schreiben",
      "table.menu": "Tabelle",
      "table.column": "Spalte",
      "table.row": "Zeile",
      "dialog.footnote": "Fußnote {0}",
      "menu.hideCode": "Code verbergen",
      "menu.propsHide": "Properties ausblenden",
      "menu.propsShow": "Properties einblenden",
      "menu.propsEdit": "Properties bearbeiten …",
      "dialog.hide": "Verbergen",
      "dialog.hideTitle": "Titel (optional)",
      "file.small": "Klein",
      "file.medium": "Mittel",
      "file.large": "Groß",
      "menu.embedFile": "In die Notiz einbetten",
      "menu.asFile": "Als Datei zeigen",
      "menu.asPicture": "Als Bild zeigen",
      "menu.showLarge": "Groß zeigen",
      "menu.embedCode": "Als Code zeigen",
      "menu.cut": "Ausschneiden",
      "menu.copy": "Kopieren",
      "menu.paste": "Einfügen",
      "menu.pastePlain": "Einsetzen und Stil anpassen",
      "menu.selectAll": "Alles auswählen",
      "menu.link": "Link hinzufügen …",
      "menu.editLink": "Link bearbeiten …",
      "menu.openLink": "Link öffnen",
      "menu.format": "Format",
      "menu.bold": "Fett",
      "menu.italic": "Kursiv",
      "menu.strike": "Durchgestrichen",
      "menu.code": "Code",
      "menu.math": "Formel aus Auswahl",
      "menu.paragraph": "Absatz",
      "menu.text": "Text",
      "menu.heading": "Überschrift {0}",
      "menu.bullet": "Aufzählung",
      "menu.ordered": "Nummerierte Liste",
      "menu.task": "Aufgabenliste",
      "menu.quote": "Zitat",
      "menu.insert": "Einfügen",
      "menu.codeBlock": "Codeblock",
      "menu.formula": "Formel",
      "menu.table": "Tabelle",
      "menu.rule": "Trennlinie",
      "menu.footnote": "Fußnote",
      "menu.page": "Unterseite",
      "menu.board": "Whiteboard",
      "board.name": "Whiteboard", "board.back": "Zurück zur Notiz", "board.undo": "Widerrufen", "board.redo": "Wiederholen", "board.tools": "Zeichenwerkzeuge", "board.color": "Farbe",
      "board.modes": "Werkzeuge", "board.kind.lasso": "Lasso: Auswählen und Verschieben", "board.kind.pen": "Stifte", "board.kind.eraser": "Radierer", "board.kind.text": "Text", "board.kind.shape": "Formen", "board.insert.image": "Bild", "board.insert.more": "Mehr hinzufügen", "board.form.auto": "Von Hand gezeichnet, sauber gemacht",
      "board.tray.min": "Werkzeuge verkleinern", "board.tray.max": "Werkzeuge zeigen", "board.tool.select": "Zeiger", "board.tool.pen": "Stift", "board.tool.mono": "Fineliner", "board.tool.marker": "Marker", "board.tool.pencil": "Bleistift", "board.tool.ruler": "Lineal", "board.tool.eraser": "Radierer", "board.tool.lasso": "Lasso",
      "board.options": "Werkzeugoptionen", "board.width": "Stärke", "board.opacity": "Deckkraft", "board.eraser.object": "Striche", "board.eraser.pixel": "Teile",
      "board.duplicate": "Duplizieren", "board.delete": "Löschen", "board.ink.any": "Andere Farbe",
      "board.insert": "Auf das Board setzen", "board.mode.draw": "Zeichenwerkzeuge", "board.insert.text": "Textfeld", "board.insert.shape": "Form", "board.insert.sticky": "Haftnotiz", "board.insert.table": "Tabelle", "board.table": "Tabelle", "board.rows": "Zeilen", "board.columns": "Spalten", "board.header": "Kopfzeile",
      "board.shape.rect": "Rechteck", "board.shape.round": "Abgerundetes Rechteck", "board.shape.ellipse": "Ellipse", "board.shape.triangle": "Dreieck", "board.shape.diamond": "Raute", "board.shape.star": "Stern", "board.shape.hexagon": "Sechseck", "board.shape.line": "Linie", "board.shape.arrow": "Pfeil",
      "board.fill": "Füllung", "board.stroke": "Rahmen", "board.textLook": "Text", "board.ends": "Linienenden", "board.arrange": "Anordnen", "board.noFill": "Keine Füllung", "board.noStroke": "Kein Rahmen",
      "board.smaller": "Kleiner", "board.larger": "Größer", "board.startArrow": "Pfeil am Anfang", "board.endArrow": "Pfeil am Ende",
      "board.align": "Ausrichten", "board.align.L": "Links", "board.align.C": "Zentriert", "board.align.R": "Rechts", "board.align.T": "Oben", "board.align.M": "Mitte", "board.align.B": "Unten",
      "board.more": "Mehr", "board.zoom": "Größe", "board.scenes": "Szenen", "board.scene": "Szene", "board.scene.n": "Szene {0}", "board.scene.prev": "Szene davor", "board.scene.next": "Nächste Szene", "board.scene.add": "Szene hinzufügen", "board.scene.none": "Noch keine Szenen. Eine Szene hält unter einem Namen fest, was das Fenster jetzt zeigt.", "board.scene.rename": "Umbenennen", "board.scene.replace": "Durch diese Ansicht ersetzen",
      "board.pen.finger": "Mit dem Finger zeichnen", "board.pen.selects": "Stift wählt aus und scrollt", "board.copyPicture": "Als Bild kopieren", "board.print": "Drucken …", "board.snap": "Am Raster ausrichten", "board.copied": "Kopiert", "board.notCopied": "Das Bild ließ sich nicht kopieren", "board.distribute.H": "Nebeneinander verteilen", "board.distribute.V": "Untereinander verteilen",
      "board.connect": "Verbinder", "board.route": "Linie", "board.link": "Verbindungslinie hinzufügen", "board.insert.link": "Link", "board.link.add": "Link hinzufügen", "board.open": "Öffnen", "board.crop": "Zuschneiden", "board.uncrop": "Ganzes Bild zeigen", "board.insertStyle": "Als Stil für Neue verwenden", "board.copyStyle": "Stil kopieren", "board.pasteStyle": "Stil einfügen", "board.group": "Gruppieren", "board.ungroup": "Gruppierung aufheben", "board.front": "Ganz nach vorn", "board.toBack": "Ganz nach hinten", "board.lock": "Sperren", "board.unlock": "Entsperren",
      "board.ink.auto": "Schwarz", "board.ink.blue": "Blau", "board.ink.green": "Grün", "board.ink.yellow": "Gelb", "board.ink.red": "Rot", "board.ink.purple": "Violett",
      "board.actual": "Originalgröße", "board.fit": "Alles zeigen", "board.grid": "Punktraster",
      "board.notSaved": "Nicht gesichert", "board.lost": "{0} Objekte konnten nicht gelesen werden", "board.cantOpen": "Das Whiteboard ließ sich nicht öffnen", "board.noPicture": "Das Bild ließ sich nicht auf das Board setzen",
      "menu.pageOpen": "Unterseite öffnen",
      "menu.pageRename": "Umbenennen",
      "page.name": "Name",
      "menu.pageStyle": "Stil",
      "page.style.row": "Zeile",
      "page.style.card": "Karte",
      "link.style.inline": "Im Text",
      "new.note": "Neue Notiz",
      "empty.title": "Noch keine Notizen",
      "toast.undo": "Rückgängig",
      "active.cannotSay": "Markdown kann einen Teil davon nicht so schreiben, wie er gezeigt wird: Er wird in schlichter Form gespeichert",
      // (what the page itself says — sidebar, tabs, menus, messages: asked for by its English words, which are the key)
      "1 file": "1 Datei",
      "1 note": "1 Notiz",
      "{0} files": "{0} Dateien",
      "{0} notes": "{0} Notizen",
      "{0} of {1}": "{0} von {1}",
      "A PDF is read here, not edited": "Eine PDF wird hier gelesen, nicht bearbeitet",
      "All Notes": "Alle Notizen",
      "All notes": "Alle Notizen",
      "All notes (Ctrl+Alt+G)": "Alle Notizen (Ctrl+Alt+G)",
      "Can't edit: {0}": "Nicht bearbeitbar: {0}",
      "Close": "Schließen",
      "Close (Esc)": "Schließen (Esc)",
      "Close Other Tabs": "Andere Tabs schließen",
      "Close Tab": "Tab schließen",
      "Close find": "Suche schließen",
      "Close tab": "Tab schließen",
      "Copied": "Kopiert",
      "Copy": "Kopieren",
      "Copy Image": "Bild kopieren",
      "Copy Link": "Link kopieren",
      "Copy code": "Code kopieren",
      "Couldn't save: {0}": "Speichern fehlgeschlagen: {0}",
      "Cut": "Ausschneiden",
      "Download": "Herunterladen",
      "File changed on disk — keeping your edits": "Die Datei wurde außerhalb geändert – deine Änderungen bleiben",
      "Find": "Suchen",
      "Find (Ctrl+F)": "Suchen (Ctrl+F)",
      "Go to PDF": "Zur PDF",
      "History Is On": "Verlauf ist an",
      "Insert and Format": "Einfügen und Formatieren",
      "Insert and Format (Ctrl+Alt+P)": "Einfügen und Formatieren (Ctrl+Alt+P)",
      "Move to Trash": "In den Papierkorb legen",
      "New Folder": "Neuer Ordner",
      "New Note": "Neue Notiz",
      "New Tab": "Neuer Tab",
      "New note or folder": "Neue Notiz oder neuer Ordner",
      "New tab": "Neuer Tab",
      "New tab (Ctrl+T)": "Neuer Tab (Ctrl+T)",
      "Next match": "Nächster Treffer",
      "Next match (Enter)": "Nächster Treffer (Enter)",
      "No additional text": "Kein weiterer Text",
      "No matches": "Keine Treffer",
      "No notes yet": "Noch keine Notizen",
      "Notes": "Notizen",
      "Only notes can be shared": "Nur Notizen lassen sich teilen",
      "Open": "Öffnen",
      "Open With…": "Öffnen mit …",
      "Open another folder (Ctrl+Alt+O)": "Anderen Ordner öffnen (Ctrl+Alt+O)",
      "Open in Default App": "In Standard-App öffnen",
      "Open in New Tab": "In neuem Tab öffnen",
      "Open in New Tabs": "In neuen Tabs öffnen",
      "Outline": "Gliederung",
      "Outline (Ctrl+Shift+O)": "Gliederung (Ctrl+Shift+O)",
      "Page name": "Name der Seite",
      "Paste": "Einfügen",
      "Previous match": "Vorheriger Treffer",
      "Previous match (Shift+Enter)": "Vorheriger Treffer (Shift+Enter)",
      "Properties": "Eigenschaften",
      "Rename": "Umbenennen",
      "Reopen Closed Tab": "Geschlossenen Tab wieder öffnen",
      "Resolve Conflicts…": "Konflikte lösen …",
      "Saved": "Gespeichert",
      "Search": "Suchen",
      "Search the quick notes": "Schnelle Notizen durchsuchen",
      "Section not found": "Abschnitt nicht gefunden",
      "Select All": "Alles auswählen",
      "Share": "Teilen",
      "Share…": "Teilen …",
      "Show": "Anzeigen",
      "Show History of This Note": "Verlauf dieser Notiz zeigen",
      "Show Large": "Groß zeigen",
      "Show in Finder": "Im Finder zeigen",
      "Sidebar": "Seitenleiste",
      "Sidebar (Ctrl+Alt+S)": "Seitenleiste (Ctrl+Alt+S)",
      "Sort and show": "Sortieren und anzeigen",
      "Sort by Date Modified": "Nach Änderungsdatum sortieren",
      "Sort by Last Opened": "Nach zuletzt geöffnet sortieren",
      "Sort by Name": "Nach Name sortieren",
      "Sync Now": "Jetzt abgleichen",
      "Sync Now: fetch what other devices wrote, and send what was written here": "Jetzt abgleichen: holen, was andere Geräte geschrieben haben, und senden, was hier geschrieben wurde",
      "Syncing…": "Abgleich läuft …",
      "The PDF viewer could not be loaded": "Die PDF-Ansicht konnte nicht geladen werden",
      "Turn Off History": "Verlauf ausschalten",
      "Turn On History": "Verlauf einschalten",
      "Use This Repository for History…": "Dieses Repository für den Verlauf nutzen …",
      "Yesterday": "Gestern",
      "1 folder": "1 Ordner",
      "{0} folders": "{0} Ordner",
      "Back to where you were": "Zurück zur letzten Stelle",
      "Back to where you were (Alt+←)": "Zurück zur letzten Stelle (Alt+←)",
      "Copy as soon as text is selected": "Kopieren, sobald Text ausgewählt ist",
      "Fit page": "Seite einpassen",
      "Fit page (H)": "Seite einpassen (H)",
      "Fit width": "Breite einpassen",
      "Fit width (W)": "Breite einpassen (W)",
      "Go to page (G)": "Gehe zu Seite (G)",
      "Outline, pages and notes": "Gliederung, Seiten und Notizen",
      "Outline, pages and notes (O)": "Gliederung, Seiten und Notizen (O)",
      "PDF": "PDF",
      "Page": "Seite",
      "Select a region to embed": "Bereich zum Einbetten auswählen",
      "Select a region to embed (R)": "Bereich zum Einbetten auswählen (R)",
      "What is copied": "Was kopiert wird",
      "Zoom in": "Vergrößern",
      "Zoom in (+)": "Vergrößern (+)",
      "Zoom out": "Verkleinern",
      "Zoom out (−)": "Verkleinern (−)",
      "Embed of the region copied": "Einbettung des Bereichs kopiert",
      "Link to the selection copied": "Link zur Auswahl kopiert",
      "Link to page {0} copied": "Link zu Seite {0} kopiert",
      "Link to the section copied": "Link zum Abschnitt kopiert",
      "Link to the page copied": "Link zur Seite kopiert",
      "Pages": "Seiten",
      "No note links to this PDF yet": "Noch keine Notiz verweist auf diese PDF",
      "This PDF has no outline": "Diese PDF hat keine Gliederung",
      "Selecting text copies a link to it": "Text auswählen kopiert einen Link dorthin",
      "Copy on select is off": "Kopieren beim Auswählen ist aus",
      "empty.text": "Notizen sind einfache Markdown-Dateien in diesem Ordner.",
      "new.folder": "Neuer Ordner",
      "new.in": "In „{0}“",
      "new.create": "Erstellen",
      "new.quickHint": "Ohne Namen heißt sie nach ihrer ersten Zeile.",
      "menu.noteOpen": "Notiz öffnen",
      "page.untitled": "Ohne Titel",
      "menu.edit": "Bearbeiten …",
      "menu.copyMarkdown": "Als Markdown kopieren",
      "menu.delete": "Löschen",
      "bar.label": "Formatierung",
      "bar.bold": "Fett",
      "bar.italic": "Kursiv",
      "bar.strike": "Durchgestrichen",
      "bar.code": "Code",
      "bar.link": "Link",
      "bar.math": "Formel",
      "bar.paragraph": "Absatz",
      "ask.title": "Änderungen in diesem Dialog übernehmen?",
      "ask.text": "Deine Eingaben hier sind noch nicht Teil des Dokuments.",
      "ask.apply": "Übernehmen",
      "ask.discard": "Verwerfen",
      "island.code": "{0}, {1} Zeilen. Eingabetaste zum Bearbeiten.",
      "island.code1": "{0}, eine Zeile. Eingabetaste zum Bearbeiten.",
      "island.math": "Formel: {0}. Eingabetaste zum Bearbeiten.",
      "dialog.gone": "Der Block ist nicht mehr in der Datei — dein Text liegt in der Zwischenablage",
      "active.large": "Großes Dokument — der Aktiv-Modus kann langsamer sein",
      "prefs.title": "Einstellungen",
      "prefs.open": "Einstellungen …",
      "prefs.general": "Allgemein",
      "prefs.editing": "Bearbeiten im Aktiv-Modus",
      "prefs.newMarkdown": "Neues Markdown",
      "prefs.page.general": "Allgemein",
      "prefs.page.appearance": "Darstellung",
      "prefs.page.sidebarPage": "Seitenleiste",
      "prefs.page.allNotes": "Alle Notizen",
      "prefs.page.history": "Verlauf",
      "prefs.page.editing": "Bearbeiten",
      "prefs.page.newMarkdown": "Neues Markdown",
      "prefs.page.latex": "Formeln",
      "prefs.page.pdf": "PDFs",
      "prefs.page.ai": "Schreibhilfe",
      "prefs.page.about": "Über",
      "prefs.group.notes": "Notizen",
      "prefs.group.writing": "Schreiben",
      "prefs.close": "Schließen",
      "prefs.docZoom": "Textgröße einer Notiz",
      "prefs.docZoom.hint": "Auch Ctrl oder Super mit + und −; Ctrl+0 für 100 %. Nur die Notiz wird skaliert, nicht die App darum.",
      "prefs.measure": "Breite der Textspalte",
      "prefs.measure.narrow": "Schmal",
      "prefs.measure.normal": "Normal",
      "prefs.measure.wide": "Breit",
      "prefs.measure.full": "So breit wie das Fenster",
      "prefs.hinting": "Schärferer Text",
      "prefs.hinting.hint": "Buchstaben werden auf ganze Pixel gesetzt: schärfer auf einem Bildschirm gewöhnlicher Auflösung, ihre Formen leicht verändert. Gilt ab dem nächsten Start der App.",
      "prefs.restartLater": "Gilt ab dem nächsten Start der App",
      "prefs.ovScope": "Zeigen",
      "prefs.ovScope.all": "Alle Notizen, nach Ordner",
      "prefs.ovScope.folders": "Einen Ordner nach dem anderen",
      "prefs.ovLayout": "Als",
      "prefs.ovLayout.tiles": "Kacheln",
      "prefs.ovLayout.list": "Liste",
      "prefs.overview": "Alle Notizen zeigt neben Notizen",
      "prefs.ovPdf": "PDFs",
      "prefs.ovImages": "Bilder",
      "prefs.ovMedia": "Ton und Video",
      "prefs.ovOther": "Alle anderen Dateien",
      "prefs.ovOther.hint": "Eine eigene Wahl, unabhängig von der Seitenleiste. Ein Rechtsklick in Alle Notizen oder in der Seitenleiste hat dasselbe unter „Show“.",
      "prefs.paragraphs": "Absätze",
      "prefs.pictures": "Bilder",
      "prefs.quick": "Schnelle Notizen",
      "prefs.quickNew": "Neue schnelle Notiz",
      "prefs.quickNew.hint": "Tasten im Feld drücken. Rücktaste setzt zurück.",
      "prefs.quickDir": "Ordner",
      "prefs.quickDir.hint": "Wo schnelle Notizen liegen. Gilt, wenn das Fenster neu geöffnet wird.",
      "prefs.pdfFormat": "Ein Link auf markierten Text wird kopiert als",
      "prefs.pdfFormat.callout": "Zitat in einem Callout",
      "prefs.pdfFormat.quote": "Zitat",
      "prefs.pdfFormat.link": "Link",
      "prefs.pdfFormat.embed": "Einbettung",
      "prefs.pdfAuto": "Kopieren, sobald Text markiert ist",
      "prefs.aiKeySection": "Gemini",
      "prefs.aiKey": "API-Schlüssel",
      "prefs.aiKey.hint": "Liegt in ~/.config/mdview/.env, nur für dich lesbar. Der Text um die Schreibmarke geht an Google, wenn ein Vorschlag angefragt wird.",
      "prefs.aiKey.placeholder": "Schlüssel einfügen",
      "prefs.aiKey.save": "Sichern",
      "prefs.aiKey.remove": "Entfernen",
      "prefs.aiKey.none": "Kein Schlüssel",
      "prefs.aiKey.set": "Schlüssel endet auf %s",
      "prefs.aiKey.env": "Aus der Umgebung (GEMINI_API_KEY)",
      "prefs.aiModel": "Modell",
      "prefs.aiModel.hint": "Leer gelassen, wird die Wahl der App gefragt.",
      "prefs.version": "Version",
      "prefs.guide": "Alles, was die App kann",
      "prefs.guide.do": "Anleitung öffnen",
      "prefs.configDir": "Einstellungsordner",
      "prefs.sidebarSort": "Notizen sortieren nach",
      "prefs.historyQuiet": "Änderungen festhalten nach",
      "prefs.historyQuiet.hint": "In einem Ordner mit eingeschaltetem Verlauf wird das Geänderte als Version festgehalten, sobald so lange nichts mehr geändert wurde – und sofort, wenn sein Fenster schließt.",
      "prefs.deviceName": "Name",
      "prefs.deviceName.hint": "Jede Version nennt das Gerät, auf dem sie entstand. Leer: der Name des Computers.",
      "prefs.deviceId": "ID",
      "prefs.history.here": "Dieser Ordner",
      "prefs.history.device": "Dieses Gerät",
      "prefs.history.github": "GitHub",
      "prefs.githubAccount": "Konto",
      "prefs.githubAccount.hint": "Für ein Projekt, das mit einem Repository bei GitHub verknüpft ist. Erreicht werden nur die Repositories, die der App dort freigegeben sind.",
      "prefs.github.none": "Nicht angemeldet",
      "prefs.github.signin": "Anmelden…",
      "prefs.github.asking": "GitHub wird gefragt…",
      "prefs.github.enter": "Bestätige diesen Code auf {0}",
      "prefs.github.open": "Code kopieren und GitHub öffnen",
      "prefs.github.cancel": "Abbrechen",
      "prefs.github.in": "Angemeldet als {0}",
      "prefs.github.out": "Abmelden",
      "prefs.github.failed": "Nicht angemeldet – {0}",
      "prefs.historyLink": "GitHub",
      "prefs.historyLink.hint": "Verknüpft bleiben dieses Projekt und das Repository gleich: Was hier festgehalten wird, geht dorthin, und was ein anderes Gerät geschickt hat, kommt hierher.",
      "prefs.githubGet": "Ein Repository holen",
      "prefs.githubGet.hint": "In einen eigenen Ordner, als Projekt, das damit verknüpft ist.",
      "prefs.github.repo": "Repository",
      "prefs.github.search": "Repositories durchsuchen",
      "prefs.github.unlinked": "Nicht verknüpft",
      "prefs.github.linkTitle": "Mit einem Repository verknüpfen",
      "prefs.github.getTitle": "Ein Repository holen",
      "prefs.github.linkDo": "Verknüpfen",
      "prefs.github.getDo": "Holen…",
      "prefs.github.private": "Privat",
      "prefs.github.public": "Öffentlich",
      "prefs.github.nofit": "Kein Repository passt",
      "prefs.github.first": "Zum Verknüpfen unten anmelden",
      "prefs.github.reading": "Repositories werden gelesen…",
      "prefs.github.norepos": "Der App ist kein Repository freigegeben",
      "prefs.github.give": "Bei GitHub auswählen",
      "prefs.github.link": "Verknüpfen…",
      "prefs.github.unlink": "Verknüpfung lösen",
      "prefs.github.get": "Holen…",
      "prefs.sync.even": "auf beiden Seiten gleich",
      "prefs.sync.new": "verknüpft",
      "prefs.sync.offline": "nicht erreicht – später wieder",
      "prefs.sync.signin": "zum Weitermachen anmelden",
      "prefs.sync.conflict": "{0} Dateien zu klären",
      "prefs.sync.conflict.one": "1 Datei zu klären",
      "prefs.historyState": "Verlauf",
      "prefs.history.is.none": "Aus",
      "prefs.history.is.paused": "Aus – die Versionen bleiben erhalten",
      "prefs.history.offDo": "Ausschalten",
      "prefs.history.is.adopt": "Aus – hier liegt ein Git-Repository",
      "prefs.history.is.foreign": "Von einem eigenen Repository geführt, nicht von dieser App",
      "prefs.history.is.project": "An",
      "prefs.history.is.inside": "An, als Teil eines Projekts",
      "prefs.history.on": "Einschalten",
      "prefs.history.adopt": "Dieses Repository verwenden…",
      "prefs.historyName": "Repository",
      "prefs.historyRoot": "Ordner",
      "prefs.historyBranch": "Branch",
      "prefs.history.noBranch": "Noch keiner",
      "prefs.historyCount": "Versionen",
      "prefs.historyLast": "Letzte Version",
      "prefs.historyChanged": "Noch nicht festgehalten",
      "prefs.history.allKept": "Nichts – alles ist festgehalten",
      "prefs.history.waiting": "%s Dateien, werden gleich festgehalten",
      "prefs.history.changed": "%s Dateien",
      "prefs.history.waiting.one": "1 Datei, wird gleich festgehalten",
      "prefs.history.changed.one": "1 Datei",
      "prefs.sort.opened": "Zuletzt geöffnet",
      "prefs.sort.name": "Name",
      "prefs.sort.modified": "Änderungsdatum",
      "prefs.sidebar": "Seitenleiste zeigt neben Notizen",
      "prefs.sidebarPdf": "PDFs",
      "prefs.sidebarImages": "Bilder",
      "prefs.sidebarMedia": "Ton und Video",
      "prefs.sidebarOther": "Alle anderen Dateien",
      "prefs.sidebarOther.hint": "Bilder, Ton, Video und andere Dateien öffnen sich in ihrem eigenen Programm.",
      "prefs.ai": "Schreibhilfe",
      "prefs.aiComplete": "Beim Tippen die nächsten Wörter vorschlagen",
      "prefs.aiComplete.hint": "In einer Pause erscheint eine Fortsetzung in Grau: Tab übernimmt sie, Ctrl+→ das nächste Wort, Esc verwirft sie. Braucht einen Schlüssel für Gemini (unten).",
      "prefs.latex": "Formeln (LaTeX Suite)",
      "prefs.latexSnippets": "Snippets",
      "prefs.latexSnippets.hint": "„sr“ wird ^{2}, „@a“ \\alpha, „dint“ ein Integral; Tab springt zur nächsten Stelle. Eigene: ~/.config/mdview/snippets.js.",
      "prefs.latexFraction": "Bruch mit „/“",
      "prefs.latexFraction.hint": "Was vor dem „/“ steht, wird der Zähler.",
      "prefs.latexMatrix": "Matrix-Tasten",
      "prefs.latexMatrix.hint": "In matrix, cases oder align: Tab schreibt „&“, Enter „\\\\“ und eine neue Zeile, Shift+Enter verlässt sie.",
      "prefs.latexTabout": "Tab verlässt Klammern",
      "prefs.latexTabout.hint": "Tab springt hinter die nächste schließende Klammer; am Ende aus der Formel.",
      "prefs.latexEnlarge": "Klammern wachsen",
      "prefs.latexEnlarge.hint": "Klammern um Summe, Integral oder Bruch werden \\left … \\right.",
      "prefs.latexBrackets": "Klammerpaare in einer Farbe",
      "prefs.latexText": "„mk“ und „dm“ im Text",
      "prefs.latexText.hint": "Als eigenes Wort getippt: „mk“ beginnt eine Formel in der Zeile, „dm“ eine abgesetzte.",
      "dialog.box": "Einrahmen",
      "prefs.lang": "Sprache",
      "prefs.lang.hint": "Der Einstellungen sowie der Menüs und Dialoge des Aktiv-Modus. Gilt für neue Fenster.",
      "prefs.startMode": "Ein neues Fenster öffnet",
      "prefs.start.last": "Im zuletzt benutzten Modus",
      "prefs.bar": "Formatierungsleiste über einer Auswahl",
      "prefs.slash": "Einfügen-Menü mit „/“",
      "prefs.slash.hint": "Ein „/“ am Anfang einer leeren Zeile öffnet es.",
      "prefs.syntax": "Markdown beim Cursor zeigen",
      "prefs.syntax.hint": "Die Zeichen von Fett, Kursiv, Code, Links und Überschriften zeigen sich dort, wo der Cursor steht.",
      "prefs.quotes": "Typografische Anführungszeichen beim Tippen",
      "prefs.wrap": "Neue Absätze umbrechen bei",
      "prefs.wrap.off": "Nicht umbrechen",
      "prefs.wrap.hint": "Nur Absätze, die neu geschrieben werden; die anderen bleiben, wie sie sind.",
      "prefs.images": "Eingefügte und abgelegte Bilder",
      "prefs.images.beside": "Neben die Notiz",
      "prefs.images.assets": "In ./assets",
      "prefs.style": "Stil für neue Elemente",
      "prefs.style.auto": "Wie im Dokument",
      "prefs.style.fixed": "Immer wie hier eingestellt",
      "prefs.bullet": "Aufzählung",
      "prefs.ordered": "Nummern",
      "prefs.emphasis": "Kursiv",
      "prefs.strongMark": "Fett",
      "prefs.langLater": "Die Sprache ändert sich in neuen Fenstern",
      "menu.image": "Bild",
      "menu.file": "Datei",
      "menu.graphic": "Grafik von Claude …",
      "graphic.title": "Grafik",
      "graphic.describe": "Beschreib, was gezeichnet werden soll – eine Schaltung, ein Logikdiagramm, ein Block- oder RTL-Diagramm, ein Schema …",
      "graphic.reference": "Referenzbild",
      "graphic.choose": "Wählen …",
      "graphic.paste": "Einfügen",
      "graphic.remove": "Entfernen",
      "graphic.draw": "Zeichnen",
      "graphic.again": "Neu zeichnen",
      "graphic.stop": "Stopp",
      "graphic.change": "Was soll sich ändern …",
      "graphic.apply": "Ändern",
      "graphic.insert": "Einfügen",
      "graphic.empty": "Hier erscheint die Grafik.",
      "graphic.drawing": "Zeichne … {0} s",
      "graphic.failed": "Es kam keine Grafik zurück",
      "graphic.hint": "Gezeichnet von Claude (Befehl claude). Beschreibung und Referenzbild gehen an Anthropic.",
      "menu.none": "Nichts gefunden",
      "menu.search": "Suchen …",
      "panel.label": "Einfügen und formatieren",
      "panel.insert": "Einfügen",
      "panel.format": "Format",
      "panel.hint": "Auf ein Element klicken oder es ins Dokument ziehen",
      "panel.search": "Suchen",
      "panel.blocks": "Blöcke",
      "panel.lists": "Listen",
      "panel.separators": "Trennlinien",
      "panel.lines": "Linie einfügen",
      "panel.line.dots": "Drei Punkte",
      "panel.line.dotted": "Gepunktete Linie",
      "panel.line.thin": "Dünne Linie",
      "panel.line.heavy": "Dicke Linie",
      "panel.tableOf": "Tabelle einfügen",
      "panel.tableHint": "Eine Tabelle mit so vielen Zeilen und Spalten wie markiert",
      "panel.tableSize": "{0} Zeilen, {1} Spalten",
      "panel.media": "Medien",
      "panel.mermaid": "Mermaid",
      "panel.graphic": "Grafik",
      "panel.both": "Block + Fokus",
      "panel.titles": "Titel",
      "panel.text": "Text",
      "panel.groups": "Gruppen",
      "panel.title": "Titel",
      "panel.subtitle": "Untertitel",
      "panel.heading": "Überschrift",
      "panel.strong": "Betont",
      "panel.body": "Text",
      "panel.content": "Inhalt",
      "panel.outdent": "Einzug verkleinern",
      "panel.indent": "Einzug vergrößern",
      "slash.columns": "Spalten",
      "columns.n": "{0} Spalten",
      "columns.addLeft": "Spalte links hinzufügen",
      "columns.addRight": "Spalte rechts hinzufügen",
      "columns.moveLeft": "Spalte nach links bewegen",
      "columns.moveRight": "Spalte nach rechts bewegen",
      "columns.equal": "Gleiche Breiten",
      "columns.unwrap": "Spalten auflösen",
      "columns.remove": "Spalte entfernen",
      "columns.delete": "Spalten löschen",
      "slash.style": "Textstil",
      "slash.list": "Liste",
      "slash.actions": "Aktionen",
      "slash.deco": "Dekorationen",
      "slash.block": "Block",
      "slash.focus": "Fokus",
      "slash.color": "Farbe",
      "slash.callout": "Hinweisbox",
      "callout.title": "Titel bearbeiten",
      "callout.fold": "Einklappbar",
      "callout.foldOpen": "Anfangs offen",
      "callout.note": "Notiz",
      "callout.info": "Info",
      "callout.tip": "Tipp",
      "callout.success": "Erfolg",
      "callout.question": "Frage",
      "callout.warning": "Warnung",
      "callout.error": "Fehler",
      "callout.bug": "Bug",
      "callout.example": "Beispiel",
      "callout.important": "Wichtig",
      "slash.colorDefault": "Standard",
      "color.red": "Rot",
      "color.orange": "Orange",
      "color.yellow": "Gelb",
      "color.green": "Grün",
      "color.cyan": "Cyan",
      "color.blue": "Blau",
      "color.magenta": "Magenta",
      "slash.duplicate": "Duplizieren",
      "slash.moveUp": "Nach oben bewegen",
      "slash.moveDown": "Nach unten bewegen",
      "slash.select": "Block auswählen",
      "slash.delete": "Block löschen",
      "slash.check": "Als erledigt markieren",
      "slash.uncheck": "Als offen markieren",
      "dialog.mathShape": "Form der Formel",
      "dialog.block": "Block",
      "dialog.inline": "In der Zeile",
      "dialog.copyLatex": "LaTeX kopieren",
      "dialog.copyPicture": "Als Bild kopieren",
      "dialog.pictureCopied": "Die Formel liegt als Bild in der Zwischenablage",
      "dialog.restore": "Verworfenes wiederherstellen",
      "dialog.form": "Formular",
      "dialog.asYaml": "Verschachtelt — als YAML bearbeiten",
      "dialog.addProperty": "Eigenschaft hinzufügen",
      "dialog.removeProperty": "Eigenschaft entfernen",
      "dialog.propertyName": "Name",
      "dialog.propertyValue": "Wert",
      "dialog.find": "Suchen",
      "dialog.found": "{0} von {1}",
      "island.hint": "{0}, {1} Zeilen. Eingabetaste zum Bearbeiten.",
      "dialog.cancel": "Abbrechen",
      "dialog.done": "Fertig",
      "dialog.copy": "Kopieren",
      "dialog.copied": "Kopiert",
      "dialog.count": "{0} Zeilen · {1} Zeichen",
      "dialog.code": "Codeblock",
      "dialog.language": "Sprache",
      "dialog.nolang": "Keine Sprache",
      "dialog.info": "Weitere Info",
      "dialog.math": "Formel",
      "dialog.blanklines": "Leerzeilen können in manchen Markdown-Programmen die Formel brechen.",
      "dialog.remove": "Entfernen",
      "dialog.frontmatter": "Eigenschaften",
      "dialog.html": "HTML",
      "dialog.table": "Tabelle",
      "dialog.deflist": "Definitionsliste",
      "dialog.callout": "Callout",
      "dialog.markdown": "Markdown",
      "dialog.size": "Größe",
      "size.auto": "Eigene Größe",
      "size.small": "Klein",
      "size.medium": "Mittel",
      "size.large": "Groß",
      "size.full": "Volle Breite",
      "menu.openPdf": "Zur PDF",
      "dialog.adjust": "Ausschnitt anpassen",
      "dialog.adjustDone": "Ergebnis zeigen",
      "dialog.adjustHint": "Rahmen oder seine Kanten ziehen; daneben ziehen für einen neuen",
      "dialog.adjustPage": "Seite {0} von {1}",
      "dialog.adjustPrev": "Vorige Seite",
      "dialog.adjustNext": "Nächste Seite",
      "dialog.wikilink": "Wikilink",
      "dialog.note": "Notiz",
      "dialog.image": "Bild",
      "dialog.alt": "Beschreibung",
      "dialog.imgtitle": "Titel",
      "active.keptEdits": "Datei wurde außerhalb geändert — deine Änderungen bleiben",
    },
  };
  const S = {
    lang: /^(en|de)$/.test((window.MdPrefs || {}).lang) ? window.MdPrefs.lang : "en", // (settings: a new window takes another)
    t(key, ...values) {
      const s = (TABLES[S.lang] && TABLES[S.lang][key]) ?? TABLES.en[key] ?? key;
      return s.replace(/\{(\d+)\}/g, (_m, i) => values[i] ?? "");
    },
  };
  window.MdStrings = S;
})();
