/* mdview — user-facing strings of the active mode, in one place so they can
 * be translated. MdStrings.t("key", …values) fills {0}, {1} …
 * The app's older strings are still inline in viewer.js and mdview.py. */
"use strict";
(() => {
  const TABLES = {
    en: {
      "mode.label": "Mode",
      "mode.edit": "Edit source",
      "mode.active": "Active",
      "mode.read": "Read",
      "mode.tip.edit": "{0} (Ctrl+Alt+1, or Ctrl+E)",
      "mode.tip.active": "{0} (Ctrl+Alt+2)",
      "mode.tip.read": "{0} (Ctrl+Alt+3)",
      "active.loadFailed": "Couldn't load the active mode",
      "active.placeholder": "Start writing…",
      "active.label": "Document",
      "link.label": "Link",
      "link.open": "Open",
      "link.edit": "Edit",
      "link.remove": "Remove",
      "link.text": "Text",
      "link.url": "Address",
      "table.rowAbove": "Insert Row Above",
      "table.rowBelow": "Insert Row Below",
      "table.rowUp": "Move Row Up",
      "table.rowDown": "Move Row Down",
      "table.rowDelete": "Delete Row",
      "table.colLeft": "Insert Column Left",
      "table.colRight": "Insert Column Right",
      "table.colMoveLeft": "Move Column Left",
      "table.colMoveRight": "Move Column Right",
      "table.align.left": "Align Left",
      "table.align.center": "Align Center",
      "table.align.right": "Align Right",
      "table.colDelete": "Delete Column",
      "table.delete": "Delete Table",
      "table.column": "Column",
      "table.row": "Row",
      "island.hint": "{0}, {1} lines. Press Enter to edit.",
      "dialog.cancel": "Cancel",
      "dialog.done": "Done",
      "dialog.copy": "Copy",
      "dialog.copied": "Copied",
      "dialog.count": "{0} lines · {1} characters",
      "dialog.code": "Code block",
      "dialog.language": "Language",
      "dialog.nolang": "No language",
      "dialog.info": "More info",
      "dialog.math": "Formula",
      "dialog.blanklines": "Blank lines can break the formula in some Markdown programs.",
      "dialog.remove": "Remove",
      "dialog.frontmatter": "Properties",
      "dialog.html": "HTML",
      "dialog.table": "Table",
      "dialog.deflist": "Definition list",
      "dialog.callout": "Callout",
      "dialog.markdown": "Markdown",
      "dialog.wikilink": "Wikilink",
      "dialog.note": "Note",
      "dialog.image": "Picture",
      "dialog.alt": "Description",
      "dialog.imgtitle": "Title",
      "active.keptEdits": "File changed on disk — keeping your edits",
    },
    de: {
      "mode.label": "Modus",
      "mode.edit": "Quelltext bearbeiten",
      "mode.active": "Aktiv",
      "mode.read": "Lesen",
      "mode.tip.edit": "{0} (Strg+Alt+1 oder Strg+E)",
      "mode.tip.active": "{0} (Strg+Alt+2)",
      "mode.tip.read": "{0} (Strg+Alt+3)",
      "active.loadFailed": "Aktiv-Modus konnte nicht geladen werden",
      "active.placeholder": "Schreib los …",
      "active.label": "Dokument",
      "link.label": "Link",
      "link.open": "Öffnen",
      "link.edit": "Bearbeiten",
      "link.remove": "Entfernen",
      "link.text": "Text",
      "link.url": "Adresse",
      "table.rowAbove": "Zeile darüber einfügen",
      "table.rowBelow": "Zeile darunter einfügen",
      "table.rowUp": "Zeile nach oben bewegen",
      "table.rowDown": "Zeile nach unten bewegen",
      "table.rowDelete": "Zeile löschen",
      "table.colLeft": "Spalte links einfügen",
      "table.colRight": "Spalte rechts einfügen",
      "table.colMoveLeft": "Spalte nach links bewegen",
      "table.colMoveRight": "Spalte nach rechts bewegen",
      "table.align.left": "Linksbündig",
      "table.align.center": "Zentriert",
      "table.align.right": "Rechtsbündig",
      "table.colDelete": "Spalte löschen",
      "table.delete": "Tabelle löschen",
      "table.column": "Spalte",
      "table.row": "Zeile",
      "island.hint": "{0}, {1} Zeilen. Eingabetaste zum Bearbeiten.",
      "dialog.cancel": "Abbrechen",
      "dialog.done": "Fertig",
      "dialog.copy": "Kopieren",
      "dialog.copied": "Kopiert",
      "dialog.count": "{0} Zeilen · {1} Zeichen",
      "dialog.code": "Codeblock",
      "dialog.language": "Sprache",
      "dialog.nolang": "Keine Sprache",
      "dialog.info": "Weitere Info",
      "dialog.math": "Formel",
      "dialog.blanklines": "Leerzeilen können in manchen Markdown-Programmen die Formel brechen.",
      "dialog.remove": "Entfernen",
      "dialog.frontmatter": "Eigenschaften",
      "dialog.html": "HTML",
      "dialog.table": "Tabelle",
      "dialog.deflist": "Definitionsliste",
      "dialog.callout": "Callout",
      "dialog.markdown": "Markdown",
      "dialog.wikilink": "Wikilink",
      "dialog.note": "Notiz",
      "dialog.image": "Bild",
      "dialog.alt": "Beschreibung",
      "dialog.imgtitle": "Titel",
      "active.keptEdits": "Datei wurde außerhalb geändert — deine Änderungen bleiben",
    },
  };
  const S = {
    lang: "en",
    t(key, ...values) {
      const s = (TABLES[S.lang] && TABLES[S.lang][key]) ?? TABLES.en[key] ?? key;
      return s.replace(/\{(\d+)\}/g, (_m, i) => values[i] ?? "");
    },
  };
  window.MdStrings = S;
})();
